### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by tisaud** [Azure/azure-remote-rendering#1]
After I changed the ID and Key according to the document, I clicked play to run the program, and unity crashed.
![image](https://user-images.githubusercontent.com/33447003/78857709-b924d480-7a5c-11ea-8596-11f44cf24734.png)
![image](https://user-images.githubusercontent.com/33447003/78857717-bd50f200-7a5c-11ea-847c-a8fa06d8b54c.png)

**Comment by C-Core** [comment]
Hi,
thank you for the bug report. 
Do you have the latest version of Visual Studio 2019 and all the other requirements installed as mentioned in https://docs.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements.
That should fix the problem.
