### ISSUE TITLE
[Question] Is WebGL publish from Unity being considered?

### ISSUE THREAD

**Issue by ElliotWood** [Azure/azure-remote-rendering#101]
Hi Team, love the library, well done.

As per title Is WebGL publish from Unity being considered? What are the current blockers or limitations?.

From the QuickStart we have a working version in Unity with WebGL as "Platform" selected 
![image](https://github.com/Azure/azure-remote-rendering/assets/1829224/4964ee76-414e-40ef-97e6-854991c0a082)

However, it only runs whilst in Unity tool and the Build step is where the errors occur due to the assemblies not currently a compile target_"Assets\Scripts\RemoteRendering.cs(4,17): error CS0234: The type or namespace name 'Azure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)"_
![image](https://github.com/Azure/azure-remote-rendering/assets/1829224/8797d5c2-3f97-497e-89ed-47c23f4faa07)

If it's not currently on radar, would it be possible to get access under an agreement to these assemblies for a custom port. 

-----------

Our goal, be able to view the outputs in a browser including interactivity. 
Ideally, we can look to create a binding or shim for webGL support.

Alternately, we have to put facade Unity WebGL project in front of an emulated Windows build (docker in AKS) and stream a RenderTexture over the network and relay input between the client builds.  _(Which feels gnarly)_
i.e.  WebGL Build <--->Windows Build <---> ARR

Looking forward to your response.

Kind Regards,
Elliot Wood

**Comment by DrewLonMS** [comment]
Hi Elliot!

Thanks for the question. We are always excited to hear what developers would like to see in Azure Remote Rendering. Please add your vote to our feedback page here: https://aka.ms/ARRfeedback. 

Can you elaborate on the challenges that web support would solve?

Thanks!

**Comment by ElliotWood** [comment]
Thanks will do. 

The challenges that web support would solve is the ability for customers to view massive 3d assets via the browser, and therefore in a contextual dashboard for the use case. 

Consider industries such as Consruction who want to do building inspections, contractor scheduling and other workflow optimizations. The ideal outcome for those customers is a web-based portal where data, charts, web maps, and large 3d models are visualized all together and integrated.

**Comment by ElliotWood** [comment]
Done -https://feedback.azure.com/d365community/idea/ddfd07d4-fd24-ec11-b6e6-000d3a4f07b8
