### ISSUE TITLE
Android Library Restrictions

### ISSUE THREAD

**Issue by astaikos316** [Azure/azure-remote-rendering#103]
Trying to leverage the Android library build on a different headset that is running Android. I have tried to run the sample but quickly just errors out with just a fatal error in logcat with no details. Is there some static configurations or settings conducted when building the .so that prevents from trying to leverage remote rendering on, for example Snapdragon Spaces Dev Kit?

**Comment by DrewLonMS** [comment]
Hi!

Currently we only support Windows Desktop, HoloLens 2, and Quest devices. Please provide the feedback for us here: https://aka.ms/arrfeedback 

Thank you.

**Comment by astaikos316** [comment]
> Hi!
> 
> Currently we only support Windows Desktop, HoloLens 2, and Quest devices. Please provide the feedback for us here: https://aka.ms/arrfeedback
> 
> Thank you.

Feedback provided as requested.
