### ISSUE TITLE
[Question] Enabling Android support in Unity 2021/2022 with XR management 4.x

### ISSUE THREAD

**Issue by NoTuxNoBux** [Azure/azure-remote-rendering#105]
After being confused for a bit as to why `Device, platform and/or XR plugin combination is not supported!` is being thrown on our Meta Quest 2 in our project, I think I pinned it down to `XR_MANAGEMENT_PLUGIN_AVAILABLE` is not being set because the assembly definition only defines it for XR Management 3.1:

```json
{
    "name": "com.unity.xr.management",
    "expression": "3.1",
    "define": "XR_MANAGEMENT_PLUGIN_AVAILABLE"
},
```

We work with Unity 2022.3, but also have projects on 2021.3 that are already on `com.unity.xr.management` 4.x mostly 'out of the box' by using recent version of Microsoft OpenXR and the MRTK.

XR Management 3.x hasn't been updated since late 2020 (3.2.17), so is there any chance of relaxing this constraint to also support 4.x? [The latest version is 4.4.0 at the time of writing](https://docs.unity3d.com/Packages/com.unity.xr.management@4.4/changelog/CHANGELOG.html).

(I'm not too familiar with version defines, but it appears to not even be a range, and 3.1 is _highly_ specific and an old version from 2020-02-07. Even within 3.x [there have been many more recent releases](https://docs.unity3d.com/Packages/com.unity.xr.management@3.2/changelog/CHANGELOG.html).)

Thanks!

**Comment by jloehr** [comment]
Hi @NoTuxNoBux,

the version define shouldn't be the issue. Providing just a single version as is, means any version equal or higher than provided, including the current 4.x version:
<img width="433" alt="image" src="https://github.com/Azure/azure-remote-rendering/assets/4631548/239d0485-30bf-497c-a24e-86eddf013c05">

I also just double-checked with our Quickstart app on Unity 2021 and 2022, which is using XR Plugin Management 4.3.3. And it is working fine.

You may be missing the checkmark for the "Azure Remote Rendering" OpenXR feature in the Android tab of the OpenXR Project Settings window. Can you double-check in your projects:
![image](https://github.com/Azure/azure-remote-rendering/assets/4631548/edc5bd27-bc3e-474d-ba8f-a76c3d5ed5a2)

**Comment by NoTuxNoBux** [comment]
Indeed, I was looking incorrectly and forgot the defines are scoped to the assembly definition defining them, my apologies.

The necessary Android feature was enabled, but due to Unity shenanigans it seems to have disabled itself again. I'll reopen if there are further issues, thanks!

**Comment by jloehr** [comment]
Glad I could help. 

You can also always check our **Project Validator** for any issues or missing configurations. You can open the **Project Validator** window by choosing the the **Validate Project** entry from the **Remote Rendering** menu in the Unity editor toolbar.

![image](https://github.com/Azure/azure-remote-rendering/assets/4631548/73cf6e70-0575-44e5-937b-30e7e832e752)
