### ISSUE TITLE
[Remote rendering problem] No errors thrown, but Unity game window not showing remote model

### ISSUE THREAD

**Issue by whatthemehek** [Azure/azure-remote-rendering#106]
I am trying to set up a default ARR project, with Unity 2022.2.0f and 3D URP. I've successfully set up a few other default ARR projects in Unity 2020, and so followed the instructions to create RemoteRenderingCoordinator and connect my Azure account. I also followed the instructions to switch the render pipeline to the one provided in the ARR assets, since I am on a 3D URP project.

When I run the project in Unity, the debug messages are all as expected- showing the progression through states until the runtime is connected, no error messages, or anything. I right-click on the RemoteRenderingCoordinator script component, click Load Test Model, it prints progress percentages of being loaded, but when it hits 100% nothing displays.

I know the problem isn't with my Azure account, as other projects using the same credentials are still working fine.

I also have no issues in the project validator or in my build settings.

**Comment by jloehr** [comment]
Hey, I was able to reproduce this issue with Unity 2022.**2**.0. It seems to be some weird behaviour of the Unity script importer. We have a fix for it in flight, but no ETA for the next release yet.

In the mean time you can work around it by either:
1. Update and use Unity 2022.3 LTS. I was unable to reproduce the bug with that version.

Or:

1. Embed the Azure Remote Rendering package in your project following this Unity guide: [Copying a Unity package from the cache](https://docs.unity3d.com/Manual/upm-embed.html#embed-cached)
2. Change the access modifier of the `HolographicRemotingCallbackPass` class from `internal` to `private` in the file `com.microsoft.azure.remote-rendering\Runtime\HybridRenderingPassFeature.cs`

**Comment by whatthemehek** [comment]
Tried both fixes, neither worked. The only things I noticed that are different than in the tutorial is that there is no USB device option in build settings in Unity 2022.2.x or 2022.3.x. Both changing the access modifier and Unity 2022.3 LTS are not working for me.

**Comment by jloehr** [comment]
Sorry to hear that neither fix worked for you. Something I forget to mention, I had to reimport the ARR package once, by right-clicking on it in the **Project Window** under the **Packages** foldout, and select **Reimport** from the context menu.

Is there any change you can provide us your project, so we can investigate further? If so, please make sure to remove any credentials beforehand.

I also have some additional questions to diagnose the issue further:
- Does any other ARR project work on your machine? You can try the Quickstart Sample project from this repository.
- In that regard, does the Quickstart Sample work, even if you upgrade that project to Unity 2022 and URP?
- Can you give us the specs of your machine: OS, Graphics Card, Graphics Driver, CPU, etc.
- Does local content render just fine, or is the entire output screen black?

**Comment by whatthemehek** [comment]
It seems like the issue is probably with URP. I started with my working project (2020.3, SRP, local and remote content), and then followed the instructions to switch to URP. The local content continues to render correctly, but the remote content stops rendering, though there aren't any error messages. I have attached a screenshot of my graphics configuration in Project Settings.

![image](https://github.com/Azure/azure-remote-rendering/assets/44351730/5b3af481-058c-4ce0-811b-2e1b9c718cd1)

**Comment by whatthemehek** [comment]
Okay, seems like for 2020.3 I fixed the bug! The issue is, in the docs it says to update the Render Pipeline setting under the Graphics tab, but not the pipeline setting under the Quality tab. Updating both to the HybridRenderingPipeline asset seems to have fixed the issue.

**Comment by whatthemehek** [comment]
Tested with 2022.2, working!
