### ISSUE TITLE
Validate Project window throws exception when camera is no called "Main Camera"

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#11]
**Problem**
The Validate Project window expects that the main camera in the scene is called "Main Camera".
If it is not, then an exception is thrown and the window fails to draw correctly.

**Repro steps**
1. Open a new scene in a project with the ARR package installed
2. Rename the camera to "MyCamera"
3. Open Validate Project window.

**Observed result**
Exceptions are thrown and the window fails to draw correctly.

**Expected result**
The main camera can be called anything with no errors thrown. Suggest using Camera.main, instead of finding by game object name.

**Comment by maapp** [comment]
Hi, just a quick heads up: We merged a fix into our internal branch and I'll update the issue once it's released publicly. Thanks again for the report and helping us to build a better product :)

**Comment by maapp** [comment]
Hi, we pushed a new release which contains a fix for this issue. Thanks for letting us know!
