### ISSUE TITLE
[Remote rendering problem] Quest2: only artifacts showing

### ISSUE THREAD

**Issue by jelmer3000** [Azure/azure-remote-rendering#113]
**Describe the problem**
On Quest2, once the rendering has started I only see a square with small blocks/artifacts in the area where the model is placed.
I suspect there's a problem with the video feed, but I don't know what. Any insights on what I could try are appreciated. 

Here's a videoclip of the problem with the default engine: https://youtube.com/shorts/F59SuC-i54I

**Comment by jloehr** [comment]
Hey @jelmer3000,

sorry to hear you are experiencing some issues with Azure Remote Rendering. To help you out and to reproduce the issue on our side, we need some more details. Can you provide the following information:

- Unity Version (I'm assuming you are using Unity)
- Unity Render Pipeline (Builtin/Legacy, Universal, HD) and its version
- Azure Remote Rendering Version
- MSAA settings

**Comment by jloehr** [comment]
Ah, I see you have updated your post and provided a video. Awesome!

I see you are using our Showcase sample. Did you upgrade it to Unity 2021 or later?
Unfortunately, there's a bug in Unitys built-in render pipeline with later Unity versions: [Unity Issue Tracker - MSAA is not applied on Quest 2 using Built-In Render Pipeline and Vulkan](https://issuetracker.unity3d.com/issues/msaa-is-not-applied-on-quest-2-using-built-in-render-pipeline-and-vulkan)
That bug creates exactly such artefacts you are seeing.

**Comment by jelmer3000** [comment]
Hey thanks for looking into this. My main goal is to just get the showcase example to work on a Quest 2. 
At first I tried with: 
- Unity 2021.3.20
- Standard Render Pipeline
- ARR 1.2.10
- 4 x AA
- Graphics API: tried Vulkan and Auto
- Color Space: tried Linear and Gamma
Today I also tried:
- Unity 2021.3.20
- URP (converted the materials, and used the MRTK conversion tool for upgrading the MRTK shaders).
- Using the HybridRenderingPipeline asset from the ARR package, tried with MSAA off and with MSAA 4X.
- ARR 1.2.10
- Graphics API: Vulkan
- Color Space: Linear

In all cases it looks like AA was NOT active, as edges were jerky. And in all cases I got the same video afrtifacts. But is that really related the video issues?


All in all what would you recommend? In the documentation it says that URP is not recommended because of performance reasons. I could upgrade to Unity 2022, or downgrade.. It would be nice if the showcase just works ;)

**Comment by jelmer3000** [comment]
Thanks, I got it working with 2020.3 and the built-in rendering pipeline. 
I also tried 2022.3 but somehow the internet connection wouldn't work there..

It's great that it now works, but it's worrying (for any custom developed app) that I couldn't get it working on recent unity versions with URP.
