### ISSUE TITLE
[Remote rendering problem] DomainUnreachable issue on Quest build using Unity 2021+

### ISSUE THREAD

**Issue by djhuds2k** [Azure/azure-remote-rendering#114]
Hi,

Having issues with creating a Remote rendering session using Unity 2021 or Unity 2022 and building for Quest 2/3.

I can get it to connect if I use 2020 but then I have issues with other features I need to use. It also works fine in the editor for 2021 and 2022.

I've tried to make it as simple as possible using your Quickstart project, but it's the same thing. I've debugged it some more and the error seems to be DomainUnreachable. There's definitely internet access and a 2020 build works fine with the same settings.

Thanks!

**Comment by FlorianBorn71** [comment]
Hi, as a very first check, could you please see whether the ARR credentials are put into the correct text field? I ask, because we have recently released a change to the Showcase/Quickstart UI that swap the first two lines. So in case you are used to put the account Id into the first field, this will now break with that "DomainUnreachable" error. Of course saved scenes should load up correctly.

<img width="362" alt="image" src="https://github.com/Azure/azure-remote-rendering/assets/44984048/62196f56-e091-4941-a1ec-5c7a4c88ab01">

**Comment by djhuds2k** [comment]
Yes, they are in the correct field and it works fine in Editor. I've just tried reversing them and same issue as well.

**Comment by FlorianBorn71** [comment]
Alright, we'll try to reproduce the problem here. We'll keep you updated.
Florian

**Comment by FlorianBorn71** [comment]
Hmm, I tried to reproduce the issue both with Unity 2021 and 2022 and it both worked (in Editor and on Quest 2).
My approach was to use off-the-shelf Quickstart sample, load it with newer Unity versions and deploy to Quest.
Could it be that some player network capabilities switched during your migration process?

Florian

**Comment by djhuds2k** [comment]
How strange... I've just tried again with a fresh download of the repo. Opened Quickstart in Unity 2022. Switched to Android and added Account details. It runs fine in Editor but as soon as I run on Quest 2, I get:

"2023/11/14 18:22:53.284 14907 14924 Warn Unity Could not create session. Error: DomainUnreachable; Message: Failed to get access token:
2023/11/14 18:22:53.295 14907 14924 Error Unity Error creating session: Failed to get access token: "

Could it be anything to do with the region I'm using? I'm using uksouth.mixedreality.azure.com

**Comment by djhuds2k** [comment]
OK, got it working! Seems like a bug in OpenXR: https://forum.unity.com/threads/unity-removes-android-permission-internet-in-the-build-apk-after-build-is-completed.1466654/

**Comment by FlorianBorn71** [comment]
Alright, thanks a lot for letting us know!
This is very helpful information if others run into the same issue.
Cheers,
Florian
