### ISSUE TITLE
[Conversion Problem] Failed conversion are no longer outputting a result.json file.

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#115]
**Describe the problem**
We've just noticed that model conversions are no longer outputting (filename).result.json files when the conversion fails. This means we can't give our users any useful information as to what is the problem with their file.

From our logs we can see that we had a result.json output for a failed conversion on the 11th Sept and then the next conversion failure we had on the 30th October (and all subsequent ones) we don't get a result.json file.

**Provide additional information**

CoversionIDs
1fdcc7fc-0959-430a-9385-8f6736052307
f647c43f-e6c0-4684-8d5e-5d4251ec1fda

**Comment by FlorianBorn71** [comment]
Hi, we'll look into that now and let you know. 
So you are saying the behavior has changed at some point second half Sept / in October, right?

**Comment by WikkidEdd** [comment]
Yes, sometime between 11th Sept and 30th October is what we believe.

**Comment by WikkidEdd** [comment]
Confirmed it's now working again. Thanks for the quick response.
