### ISSUE TITLE
[Question] Camera Upside down when i start a remote session on quest pro

### ISSUE THREAD

**Issue by MirkoCzo** [Azure/azure-remote-rendering#117]
Hello,

I am currently using the showcase template.

When I build it in Unity on my PC, it works very well. However, when I play it on my Quest Pro, I encounter two problems:

I have to set the target eye to both even though I have already done so.
When I start a remote rendering session, the camera flips upside down and I can only see with one eye.
Does anyone know where these problems originate from?

**Comment by jloehr** [comment]
Hey there,

By "play it on my Quest Pro", do you mean you built an `.apk`, deployed it to your device and are running it directly on it? Or are you using any PC to Quest streaming, and are still running it in your Editor?

**Comment by MirkoCzo** [comment]
Hey, thanks for the fast reply.

I'm using my PC to stream the quest with the quest link, and it is still running in the editor.

I tried to build an APK, but it didn't work. However, it is another problem.

**Comment by jloehr** [comment]
Oh, I see. ARR doesn't support streaming from PC (Editor or standalone app) to Quest yet. We do have a backlog item for that, but no ETA. For now, you have to build an `.apk` of your app and deploy it directly to device.

I'm closing this issue. If you have any issues with building the `.apk`, please open a new issue.
