### ISSUE TITLE
[Question] I can't open my .APK on quest pro

### ISSUE THREAD

**Issue by MirkoCzo** [Azure/azure-remote-rendering#118]
Hey I'm actually coming from that first problem: https://github.com/Azure/azure-remote-rendering/issues/117

So I ran into another problem: I couldn't create an .APK, I fixed some problems myself and now I can create one, but I'm still getting errors.

When I create an APK, I get these errors: 

![errors](https://github.com/Azure/azure-remote-rendering/assets/117487948/6349752c-8bc7-468c-adfe-dea8a5a5d0be)

I tried to upload it to my device with ADB, it works but I can't open it.

**Comment by jloehr** [comment]
11 seconds for an `.apk` build is pretty fast for Showcase.

> I fixed some problems myself 

Can you elaborate what these issues were and how you fixed them? Usually Showcase should be ready to go and build without issue given the correct Unity version.

Just to make sure, have altered Showcase in any way, other than entering your ARR credentials? Which Unity version are you using? Have you correctly installed the Android Unity module? And have you switched to the Android Platform before building?

**Comment by MirkoCzo** [comment]
I had this type of error: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10449#issuecomment-1111163353 so I deleted the facing in this script:
![bug2](https://github.com/Azure/azure-remote-rendering/assets/117487948/0a361e37-709d-46ef-94a5-c8749ac6d403).

I'm not sure about all the other changes I made because at first it didn't really work well but I started to get it working at least through the editor and now I'm trying through the headset it was some changement about graphic settings some changement on the camera because of the flipping uspide down.

You're right about the low build time. I don't know why it happened, but now it seems more likely.: 
![image](https://github.com/Azure/azure-remote-rendering/assets/117487948/db4fcb45-2867-4e6b-bf86-0239c513df9b)


And yes i installed the Android Unity Module and I've switched to android platform :
![image](https://github.com/Azure/azure-remote-rendering/assets/117487948/f2b06506-00d8-4e8d-a471-112c06be08ec)

**Comment by jloehr** [comment]
Your mentioned fix is for URP, but Showcase is still on the (legacy) build-in render pipeline. So you shouldn't need it.

Can you do a clean clone/checkout of the Showcase sample, open Unity with the Android platform, build the `.apk` right away without any other changes, and see if that works without issues? That way we can rule out any of your changes.

Also which Unity version are you using?

**Comment by ChristopherManthei** [comment]
Hi @MirkoCzo , if you are still having problems, please re-open this ticket or create a new one, Thanks!
