### ISSUE TITLE
[Question] Showcase App - Storage Model Container

### ISSUE THREAD

**Issue by reneschulte** [Azure/azure-remote-rendering#12]
I struggle to configure the sample correctly with the custom models Storage Container. I'se set name and key correctly. 
Can you provide an example what value should be entered at "Storage Model Container"? 
I've entered arroutput as this is the blob container storing the models but in subfolders as you can see below. Do the arrasset files have to be in the root folder? 
![image](https://user-images.githubusercontent.com/7439129/84785808-36843c80-afec-11ea-992f-b8c16ac28fd8.png)

**Comment by florolf1** [comment]
I use the same folder structure. You just need to enter your root folder name. In your case, just like in the documentation, enter "arroutput".

**Comment by reneschulte** [comment]
That's what I have indeed but still it won't show me my models.  
![image](https://user-images.githubusercontent.com/7439129/84788481-74cf2b00-afef-11ea-9b3c-8ff38f9aec70.png)

**Comment by reneschulte** [comment]
The rest are these values from the Azure portal:
![image](https://user-images.githubusercontent.com/7439129/84788825-dd1e0c80-afef-11ea-84bb-b8162b9f2866.png)

**Comment by florolf1** [comment]
Did you link your BlobStorage with RemoteRendingAccount and assigned the three roles?

**Comment by reneschulte** [comment]
Yes. They are linked and the Quickstart sample works well with my custom models.

**Comment by florolf1** [comment]
You dont need to link your BlobStorage with your RemoteRenderingAccount for the Quickstart sample (you just provide the SAS URI).
I had similar problems. My mistake was not having the accounts properly linked. Sometimes, when you add a new role, you are not able to see your Remote Rendering account.
If the RoleSection in your BlobStorage does not look like the following picture, maybe this will [help](https://docs.microsoft.com/en-us/azure/remote-rendering/resources/troubleshoot#cant-link-storage-account-to-arr-account).
![Bildschirmfoto 2020-06-16 um 16 58 23](https://user-images.githubusercontent.com/29608141/84791651-32a7e880-aff3-11ea-9948-16cc66bd7e29.png)

Can you see you custom models inside Unity Editor?

**Comment by sebastianpick** [comment]
There is really nothing to add here :). Thank you for doing all the explaining, @florolf1. The important part with storage accounts in the ShowcaseApp really is to properly link up a storage account with the respective remote rendering account. Afterwards it should just work by providing the Storage Account Settings as was already done.

One thing worth pointing out, however, is that the asset enumeration might take a bit of time (a few seconds) if there are really large numbers of files/assets in the container. It does not seem to apply here, but it is something to keep in mind.

**Comment by reneschulte** [comment]
Thank you guys. I have the Role assignments and just created them freshly again. Still same it won't enumerate the models in the UI on the HL2. Interestingly it shows them when I run it in the Unity Editor. 
HL2 built I tried Master ARM and ARM64. Both just show the built-in Engine. 
Code: d838a99be65bb0d83f6015e1aaad7ed6c3a50d66

**Comment by florolf1** [comment]
Check if you can see your custom models inside the Unity Editor.
If you can, you probably facing the same issue like me.
Try to use Unity Version 2019.3.15f1 +.
We figured out that the HTTP error is on Unity side. Using a newer or older 2018 LTS will fix this issue.

**Comment by reneschulte** [comment]
Thanks @florolf1 It works in Unity Editor and shows the Models but not on HL2. 
I just rebuilt freshly with Unity 2019.3.15f1 as Master build config for ARM64 but still it won't show the models on HL2. 
What build config are you using? Maybe it only shows the issue on ARM64 and/or build config Master.

**Comment by florolf1** [comment]
I am using Unity Version 2019.3.15f1, VS 16.6.1 and SDK Version 10.0.18362.0 and ARM64/Release Config.
Try to not use the configuration profile. Use instead the arr.account.xml in StreamingAssets Folder.
And you can find the UnityPlayer.log in the Device Portal(User Folders\LocalAppData<your app>\TempState\UnityPlayer.log) to check if it is a HTTP Error or not.

**Comment by reneschulte** [comment]
Danke @florolf1 

Do you have a sample arr.account.xml somewhere (w/o your credentials)? I can't find one. I guess that might be it.

**Comment by sebastianpick** [comment]
@reneschulte I must investigate why arr.account.xml is not in the repo. You can alternatively use arr.overrides.xml which can be found in AzureRemoteRenderingShowcase/.documents/.samples. Please refer to the Showcase App documentation for details on how to use it.

**Comment by reneschulte** [comment]
Sounds good @sebastianpick LMK once you have the arr.account.xml committed. 
Also weird the Unity UI configs only work in the Editor but not in the deployed app.

**Comment by florolf1** [comment]
> All settings are optional if their values are set in the arr.account.xml file. The arr.account.xml file can be placed under Unity's StreamingAssets directory. If this file exists, the app will use the file's settings, instead of those within the configuration profile.
> 
> The arr.account.xml file is not tracked by git (as defined in the app's .gitignore), preventing accidental commits of private/secret information. So it is preferred to use arr.account.xml instead of adding your private account settings to the MRTK's configuration profiles.

You can find all informations inside the ARRShowcase Folder [here](https://github.com/Azure/azure-remote-rendering/blob/master/Unity/AzureRemoteRenderingShowcase/.documents/app-usage.md)

**Comment by reneschulte** [comment]
Thanks @florolf1 Fully understand that. 😁
@sebastianpick was just mentioning there should also be an arr.account.xml sample file in AzureRemoteRenderingShowcase/.documents/.samples but it's not there (yet). Always easier to just adapt a sample XML file than having to create one from scratch with an XSD. 😉
But seems the arr.account.xml and arr.override.xml have the same schema so I could use the arr.override.xml sample file for now. Correct?
Thanks for your help. Very much appreciated. 🙏

**Comment by florolf1** [comment]
Correct. I tested both with the same schema, and it worked for me.

**Comment by reneschulte** [comment]
Added the arr.account.xml and also tried arr.overrides.xml in the UserData folder on the HL2 like described in the docs. 
Still no Models are shown on the HL2. Editor shows the list of models just fine. So somehow related to the HL2. Build ARM64 Release with 18xxx SDK. 

Here's the HL2 log. One line mentions:  Failed to load container data. Reason: An error occurred while sending the request 
Could this be it? 

```
Logging to C:/Data/Users/rschulte/AppData/Local/Packages/Azure.Remote.Rendering.Showcase_awaf3f2xac5x2/TempState/UnityPlayer.log
Loading native plugins
  Loading AudioPluginMsHRTF.dll
  Loading Microsoft.Holographic.HybridRemoting.dll
  Loading RemoteRenderingClient.dll
Module information:
 Built with Compiler Ver '191627012'
 Built from '2019.3/staging' branch
 Version is '2019.3.15f1 (59ff3e03856d)'
 Release build
 Application type 'D3D'
 OS 'Windows 10 (10.0.19041)'
PlayerConnection initialized from C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/Azure.Remote.Rendering.ShowcaseVS.Release_ARM64.rschulte/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55211
Multi-casting "[IP] 192.168.197.145 [Port] 55211 [Flags] 2 [Guid] 2173188267 [EditorId] 0 [Version] 1048832 [Id] UWPPlayerARM(HL205) [Debug] 0 [PackageName] Azure.Remote.Rendering.Showcase_awaf3f2xac5x2 [ProjectName] <no name>" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55211]
PlayerConnection already initialized - listening to [0.0.0.0:55211]
[Subsystems] Discovering subsystems at path C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/Azure.Remote.Rendering.ShowcaseVS.Release_ARM64.rschulte/Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Qualcomm(R) Adreno(TM) 630 GPU (ID=0x45373230)
    Vendor:   
    VRAM:     1932 MB
Initialize engine version: 2019.3.15f1 (59ff3e03856d)
WARNING: Shader Unsupported: 'Hidden/Universal Render Pipeline/ScreenSpaceShadows' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
ERROR: Shader Hidden/Universal Render Pipeline/ScreenSpaceShadows shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
D3D11 device created for Microsoft Media Foundation video decoding.
Created eye textures with a "texture array" layout.  The "single-pass instancing" stereo mode will be used.

Windows Mixed Reality spatial locatability state changed to Active. 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 324)

Shader 'BlobWireFrame': fallback shader 'Unlit' not found
UnloadTime: 1.467500 ms
Unable to register IMixedRealityInputDeviceManager service with a null concrete type.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders()
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__60_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(IEnumerable`1, Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Photon is not installed. Inorder for the multi-user experence to function, please install the Photon PUN SDK. See this sample's documentation for details. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unity graphics device:
ID: 1161245232 Name: Qualcomm(R) Adreno(TM) 630 GPU
Type: Direct3D11 Version: Direct3D 11.0 [level 11.1]
Failed to load container data. Reason: An error occurred while sending the request 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Sharing service is still starting up. Unable to complete request.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Extensions.SharingService:SetProperty(String, Object)
Microsoft.MixedReality.Toolkit.Extensions.SharingServiceTarget:SetProperty(String, Object)
Microsoft.MixedReality.Toolkit.Extensions.SharingTarget:SetProperty(String, Object)
SharableMenu:SendPointerMode(Object, IPointerModeChangedEventData)
Microsoft.Azure.SpatialAnchors.SessionUpdatedDelegate:Invoke(Object, SessionUpdatedEventArgs)
Microsoft.MixedReality.Toolkit.Extensions.PointerStateService:set_Mode(PointerMode)
HandMenuHooks:SetPointerMode(PointerMode)
HandMenuHooks:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Physics.PhysX] BV4 midphase only supported on Intel platforms.
UnityEngine.PhysicsScene:Query_SphereCast(PhysicsScene, Vector3, Single, Vector3, Single, RaycastHit&, Int32, QueryTriggerInteraction)
UnityEngine.Physics:Raycast(Vector3, Vector3, RaycastHit&, Single, Int32)
Microsoft.MixedReality.Toolkit.Physics.MixedRealityRaycaster:RaycastSimplePhysicsStep(RayStep, Single, LayerMask[], Boolean, RaycastHit&)
Microsoft.MixedReality.Toolkit.Input.DefaultRaycastProvider:Raycast(RayStep, LayerMask[], Boolean, MixedRealityRaycastHit&)
Microsoft.MixedReality.Toolkit.Input.FocusProvider:QueryScene(IMixedRealityPointer, IMixedRealityRaycastProvider, LayerMask[], PointerHitResult, Int32, Boolean)
Microsoft.MixedReality.Toolkit.Input.FocusProvider:UpdateGazeProvider()
Microsoft.MixedReality.Toolkit.Input.FocusProvider:Update()
Microsoft.MixedReality.Toolkit.Input.RemoteFocusProviderNoCollider:Update()
Microsoft.MixedReality.Toolkit.<>c:<UpdateAllServices>b__63_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(IEnumerable`1, Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update()

[C:\buildslave\physx\build\physx\source\geomutils\src\mesh\GuMidphaseInterface.h line 175] 
(Filename: C:\buildslave\physx\build\physx\source\geomutils\src\mesh\GuMidphaseInterface.h Line: 175)

Can not play a disabled audio source
UnityEngine.AudioSource:PlayOneShot(AudioClip)
UnityEngine.Events.UnityAction`1:Invoke(T0)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent:Invoke()
Microsoft.MixedReality.Toolkit.UI.PressableButton:Update()

[C:\buildslave\unity\build\Modules/Audio/Public/AudioSource.cpp line 2234] 
(Filename: C:\buildslave\unity\build\Modules/Audio/Public/AudioSource.cpp Line: 2234)

Trimming D3D resources.

```

**Comment by sebastianpick** [comment]
Yes, the error you mentioned is a result of the file enumeration REST call failing. I will investigate why the HL2 might fail to send out the HTTP request.

**Comment by sebastianpick** [comment]
This is interesting. Before, @florolf1 was able to resolve this issue with the Unity version you are also using. Can you confirm that you used precisely the same SDK version 10.0.18362.0 (with VS 16.6.1) as him?

**Comment by reneschulte** [comment]
Moin Sebastian. 😁

Almost the same. See details below. 

Also here is the HL2 version: 

![image](https://user-images.githubusercontent.com/7439129/85028067-edaebe00-b17a-11ea-8e8c-b94364b9877a.png)



![image](https://user-images.githubusercontent.com/7439129/85027880-b7713e80-b17a-11ea-80a9-df76d517bb11.png)


![image](https://user-images.githubusercontent.com/7439129/85027970-d079ef80-b17a-11ea-95ae-7a576d3475d4.png)

**Comment by sebastianpick** [comment]
That looks like it is the same in the critical parts. Have you always been running the HL2 in the same network and is it the same as the one you use when running from the Unity Editor? Would it be possible for you to try another one?

**Comment by reneschulte** [comment]
Same Wi-Fi network on all devices. All on my home network here. Our own apps with ASA and loading models from OneDrive, using SignalR on Azure, etc. work just fine. Unlikely the network. Again, same like my PC and other services work just fine. And the ARR Showcase can load the built-in engine and works super smooth.

**Comment by sebastianpick** [comment]
Thanks for the information. I will try to escalate the problem internally as we are fairly certain that it is not an Azure Remote Rendering related issue. In the meantime, you could also try to open a thread in the HoloDevelopers Slack Channel.

**Comment by maapp** [comment]
Hey Rene,
I came across this thread https://forum.photonengine.com/discussion/15355/failed-to-connect-to-server-after-testing-each-known-ip-on-universal-windows-platform

And this on Slack:
"Here's what to do specifically:
- Uninstall Windows SDK Version 10.0.19041.0 and install previous version of Windows SDK (i.e. 10.0.18362.0).
- In Unity Build Settings and Visual Studio project properties, make sure that the target SDK version is set to the correct version."

I haven't tested myself yet but there might some bad interaction between having the 10.0.19041.0 Window SDK installed. Could you check if you have it installed?

**Comment by reneschulte** [comment]
Hallo Marc!

Yes, I have Win SDK 19041 installed. Uninstalling now. Will try with 18362 which I also have already installed.

**Comment by maapp** [comment]
Great, one more note from the Slack discussion:
"Then restart the computer (to be safe), delete the generated output folder and rebuild it from inside Unity. That should get you back to good."

**Comment by florolf1** [comment]
Interesting. When i was facing the problem, I had the new win sdk installed, even if the old version was selected as target SDK in unity.
I then uninstalled the new sdk version and created the project from scratch with unity 2019.3.15 the error dissapeard.

**Comment by reneschulte** [comment]
Alright folks! That was it! 🎉

I uninstalled 19041. Did not reboot but cleared the build output and Unity's Library folder. 
Built ARM Release targeting 18362 with VS 2019. Boom. Works! ✨

Thanks gentlemen for you help and staying on top of it. 🙏

**Comment by maapp** [comment]
For completeness. This is apparently a known issue on the Unity side:
https://issuetracker.unity3d.com/issues/system-dot-net-dot-socket-objects-throw-argumentexception-in-il2cpp-after-installing-windows-sdk-2004

A fix will come to 2018.4 & 2019.4 in the future.

**Comment by reneschulte** [comment]
Danke Marc! Good to know and not surprisingly it's yet again a combo of a certain Unity version with Win SDK,

**Comment by flufy3d** [comment]
hello guys ,I have the same issue here.it's work on unity Editor .but not work on hololens2 .after I upgrade unity 2019.3 to unity 2019.4 problem sovled
