### ISSUE TITLE
laz file does not render correctly

### ISSUE THREAD

**Issue by hectorm-bmg** [Azure/azure-remote-rendering#120]
I have a laz file that I'm able to display in another 3D tool but it does not render correctly in ARRT.

sessionId: Arrdaf57ddb3e5a84968e2aab1958b6751c

**Comment by mafaldag1** [comment]
Hi! Thank you for bringing up the issue.
 
Did the rendering of your model show only a checkerboard background? It's possible that the model you were trying to render is too big for a standard size session. Please double check the sizes here [Server sizes - Azure Remote Rendering | Microsoft Learn](https://learn.microsoft.com/en-us/azure/remote-rendering/reference/vm-sizes)
 
If you'd like to share the file for us to investigate, please open a ticket in https://learn.microsoft.com/en-us/azure/remote-rendering/resources/support

**Comment by hectorm-bmg** [comment]
I switched to Premium and was able to see the model. Thanks!

**Comment by mafaldag1** [comment]
Glad to hear! I'm closing this issue, if you have any other problems please let us know :)
