### ISSUE TITLE
[Question] Is it possible to configure the camera as orthographic?

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#123]
We're looking to make some improvements to our desktop app to allow our users to position models more easily. One desirable feature would be to switch to an orthographic view similar to what you might have in the content package like Blender or Unity. This helps when trying to align objects. 

We have had a look at the documentation and the APIs, but couldn't see anything. Is there anything already that would allow us to do this? If not, can we make a request for that feature?

Just to clarify, we're only talking about changing the main view on a 2D display to orthographic. We wouldn't expect to have multiple viewpoints.

**Comment by jumeder** [comment]
Hi @WikkidEdd! Unfortunately, this is currently not possible. The desktop simulation API does not allow you to specify the projection matrix manually, and everything is indeed a perspective projection under the hood in ARR.

I'm logging your feature request internally with the team, but I have to put a disclaimer on it as in all likelihood it will not be something we can realistically tackle short-term.

**Comment by WikkidEdd** [comment]
Ok, that is good to know, thanks. You can close the ticket if you wish.
