### ISSUE TITLE
[Question] Hand ray and pointer don't work when inside a 3D model in ShowCase

### ISSUE THREAD

**Issue by ydev0927** [Azure/azure-remote-rendering#124]
View "Engine (Built-in)" in ShowCase.
Resize it to be huge and go inside it.
Confirm that the hand ray and pointer are not visible.

I confirmed this in ShowCase version 1.2.27.
Version 1.1.33 shows the hand ray and pointer.

How do I see the hand ray and pointer inside the model in version 1.2.27 (or later)?

**Comment by jloehr** [comment]
Hi @ydev0927, thanks for bringing this up.

This is a known regression in Showcase due to the reworked pointer handling. We have fix for it in flight, that will be deployed with our next release.

**Comment by ydev0927** [comment]
Hello, jloehr.

Thank you for answer.
Ok, I'm waiting for a next release.

**Comment by ydev0927** [comment]
Thank you contributors.
Version 1.2.32 Fix confirmed.
https://github.com/Azure/azure-remote-rendering/releases/tag/1.2.32
