### ISSUE TITLE
[Question] Showcase App - How to get built-in engine and custom models listed

### ISSUE THREAD

**Issue by reneschulte** [Azure/azure-remote-rendering#13]
Thanks to the help here I finally got my custom models from Blob storage to show up in the app. But seems the built-in engine is not listed in the Models list then. I'd like to have both, built-in engine and custom models. Is there a way to have that? Could I copy the built-in engine from somewhere into my Blob storage container or something?

**Comment by florolf1** [comment]
I'd be interested too. I couldn't find the build-in model for download in the documentation.

**Comment by reneschulte** [comment]
Also @florolf1 if you have some cool hi poly models to share, I'm always looking for some to push the boundary. 😉

**Comment by florolf1** [comment]
The building models i use have been created in-house and are not publicly available, sorry.
BTW, have fun at the [XR-Expo](https://xr-expo.com/) tomorrow.

**Comment by reneschulte** [comment]
Thanks. Should be fun and I will also show some ARR stuff during my talk. Of course right. 🤩

**Comment by reneschulte** [comment]
I just modified the code a little bit so it adds it at the end of the list. Of course not super robust and you can end up with 2 engines in the list but works for my demo and might be useful for others as well as a quick workaround.
![image](https://user-images.githubusercontent.com/7439129/85570059-5abacb80-b633-11ea-93d5-630e690ababb.png)

**Comment by maapp** [comment]
This request actually already came up internally :) Let's see if we can make it happen sooner than later.

**Comment by stefanhessel** [comment]
Hi,

just a quick update. This will be in the next release. There is a new option in the ConfigurationProfile for RemoteRenderingService to always include the default models:

![image](https://user-images.githubusercontent.com/48021740/87174787-fc9b1300-c2d7-11ea-91e1-cb964b0e0a70.png)

Thanks for your feedback!

**Comment by justinLifelike** [comment]
Hi @reneschulte, 

How did you accomplish loading up custom models?

**Comment by reneschulte** [comment]
Follow this tutorial: 
https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/convert-model

**Comment by justinLifelike** [comment]
@reneschulte Thank you for answering so quickly! 
I got to this point where it is working with the example engine 
and I converted a model using ARRT and your tutorial, much love for that Rene! 
But now I dont know where I can find my SAS URI 
![image](https://user-images.githubusercontent.com/89152236/135480528-35ddba3a-8ddb-4354-b86a-bfdddcd5d4fa.png)

**Comment by FlorianBorn71** [comment]
Hi Justin,
you need to put in a SAS token of your converted model. `builtin://Engine` is just a hardcoded URI that maps to the sample engine model.
If you want to create a SAS token for any file in your blob storage, you can refer to this doc:
https://docs.microsoft.com/azure/remote-rendering/quickstarts/convert-model#optional-re-creating-a-sas-uri
