### ISSUE TITLE
Can't do anything but to scale a rendered model inside a build application

### ISSUE THREAD

**Issue by nooxouille** [Azure/azure-remote-rendering#14]
Hi,

## Bug description

While inside an application build on HL2, the only interaction I can have with a remote rendered model is scaling. 
Rotating and translating do not work on the model.
I tried with both the test model (the engine) and a custom model (bigger than the test model although with less polys).

Inside the editor, interaction are working well (rotation, translation, scaling)

Checking via the editor, the box  collider is active and inside the app, the bounding box is working well.

## Setup

- MRTK 2.4
- Unity 2019.4 LTS
- Legacy pipeline

## Additional Info

A short video showing off the issue.

https://www.youtube.com/watch?v=3gDdLHyuUKM&feature=youtu.be

**Comment by janekvap** [comment]
Hi Mauryl, 
can you provide a snippet that takes care of the position changes? Are multiple scripts touching the same object?
Does the ShowcaseApp work for you?

It looks like some script is resetting the position, it might be script execution ordering being different between editor and build app causing this to happen only on device?

**Comment by nooxouille** [comment]
Hi @janekvap !

I haven't tested the showcaseApp. 
I have just followed the tutorials inside a newly created project.

I do not have any other interactions on the models beside the ones allowed by the (cloned) ObjectManipulator.cs and the only scripts I am using are the ones that I have created while going through the tutorials.

![image](https://user-images.githubusercontent.com/2682226/87683755-bd5e3d80-c781-11ea-8839-fef5403bbaa2.png)

**Comment by janekvap** [comment]
Sorry for long pause, I was out of office.
I can reproduce the issue with the stock tutorials and there seeems to be more than one comparing editor to device run.
I will let you know if there is fix you can try locally before we make it on our side and get it into some release.

**Comment by nooxouille** [comment]
Hey! Thx for the update!
I will wait then :)

**Comment by janekvap** [comment]
There is WorldAnchor added to the entity root which prevents it from moving.
You can go to RemoteRenderingCoordinator.cs line 362 (LoadModel) and remove the code adding WorldAnchor component from there. 
If you need it the world anchor should be on object one more level up, that is not movable and acts as a stage for models.

**Comment by nooxouille** [comment]
Ah! It is working like a charm ! Many thanks !
