### ISSUE TITLE
Ampersand character in file name causes conversion to fail [Conversion Problem]

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#15]
**Describe the problem**

Attempting to convert an asset with a filename which includes an ampersand (possibly other characters also, I haven't tested) i.e "PLOTS12&3REVF3DViewExport.fbx" will cause an internal server errors during the conversion process.

"Conversion status update:" "converting" -> "conversion_failed" ". Message: " "InternalServerError: ConversionProcessError - An internal conversion process error occured." 

**Desired behavior**
Either the conversion process should handle the ampersand character in the file name or the error message should be more informative to allow the user to remedy the issue.

**Comment by MalcolmTyrrell** [comment]
Yep. I'm seeing this too. Thanks for bringing it to our attention! We'll try to get it resolved in a release soon.

**Comment by MalcolmTyrrell** [comment]
Hey there. Just to say that we're working on this and we should have a fix soon. We'll let you know when it's resolved.

**Comment by MalcolmTyrrell** [comment]
This should be resolved now. Thanks for filing the bug!
