### ISSUE TITLE
ARR Showcase session configuration buttons aren't removed when Account Domains are removed

### ISSUE THREAD

**Issue by ForrestTrepte** [Azure/azure-remote-rendering#16]
**Describe the problem**

If a user removes account domains in the Remote Rendering Service settings the AppMenu buttons remain active and available. For example, if I only have a service in the East US region then the buttons of the AppMenu will look like this:

![AppMenuOneDomainExtraButtons](https://user-images.githubusercontent.com/17389739/91108897-1dbc8680-e62e-11ea-9901-1901f4831d80.jpg)

**Provide additional information**

Repro steps:
1. Using Unity 2019.3.15f1, open the ARR Showcase from commit f2e757b
1. Open the SampleScene
1. In MixedRealityToolkit > RemoteRenderingService > Configuration Profile edit Account Domains and Account Domain Labels to only have a single entry for the eastus region. I expect that many developers may not have accounts in all regions and may just want to use a single region like this.
1. Hit Play in the editor.
1. In the Create Session prompt click No.
1. In the app toolbar click Session > Configure.

result: Session Configuration menu shows East US twice, West Europe, and Southesast Asia
expected: Session Configuration menu shows only East US

It appears that in [SessionRegionButton](https://github.com/Azure/azure-remote-rendering/blob/master/Unity/AzureRemoteRenderingShowcase/arr-showcase-app/Assets/App/Utilities/Buttons/SessionRegionButton.cs).UpdateDomainAndLocation, although it dynamically responds to AccountDomains and AccountDomainLabels by changing its button text and domain, the buttons don't disable themselves if there are fewer entries in the list. It is even possible to select one of these other regions and appear to be connecting to it.

**Comment by FlorianBorn71** [comment]
Hi, thanks for your feedback! We'll have a look into this and keep you updated.
Cheers,
Florian

**Comment by ForrestTrepte** [comment]
Thanks @FlorianBorn71. #17 is a potential solution. I don't know if it's the best approach, but it worked for me.

**Comment by FlorianBorn71** [comment]
That's appreciated a lot! We'll have a look into it asap!
Florian

**Comment by ForrestTrepte** [comment]
Actually, I'm realizing I may not fully understand how this works. The configuration profile has the ability to specify multiple account  domains coresponding to Azure regions. But there is only a single AccountId and AccountKey. I had thought that I created my remote rendering account in a particular region. So what does it mean to select a different region in the showcase? Can my remote rendering account in East US be used to spin up sessions running in other regions?

**Comment by FlorianBorn71** [comment]
This question is a common one, and this part in the docs can easily be missed:

https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/create-an-account#account-regions

Summarized, you do create the account in a region that is suitable to you, but you can run the service in other regions, too. In the latter, you pick the region that is physically the closest to you for the best latency. Available regions are listed here: https://docs.microsoft.com/en-us/azure/remote-rendering/reference/regions

I hope this helps?
Florian

**Comment by ForrestTrepte** [comment]
Aha! Thanks, yes that helps.

**Comment by ForrestTrepte** [comment]
And that makes this issue less important. Since you can run anywhere, why would you want to limit the regions available to end-users? Perhaps you shouldn't remove regions from Account Domains and then this issue is moot.

However, it does seem that the code in [SessionRegionButton](https://github.com/Azure/azure-remote-rendering/blob/master/Unity/AzureRemoteRenderingShowcase/arr-showcase-app/Assets/App/Utilities/Buttons/SessionRegionButton.cs) is designed to dynamically respond to changes in the Account Domains list. So it was a little surprising that it didn't work correctly if entries are removed.

However, I'm not longer convinced this is an important issue so you could close it if you would like.

**Comment by FlorianBorn71** [comment]
Great to hear. Anyway, we are always interested in improving sample quality so we will definitely add the fix, esp. since we got this one served on a silver platter ;-)

Cheers,
Florian

**Comment by stefanhessel** [comment]
Your fix is will be in the next release, see also https://github.com/Azure/azure-remote-rendering/pull/17#issuecomment-685783211

Thank you for your feedback!

Cheers,
Stefan
