### ISSUE TITLE
[Remote rendering problem] Auto-Renew Session behaviour is inconsistent and excessive

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#19]
### **Describe the problem**

If you don't use the Auto-Stop session behaviour, the logic for auto-renew becomes quite important to ensure you're not running ARR sessions for longer than necessary.

There are two problems with the current auto-renew behaviour (version 0.1.76), the criteria from when to extend and the extension duration.

**Extension Criteria** - The logic for determining when a session should extend is inconsistent depending on the code path.
1. The first code path is when you're creating a new session from the client. This defines the time at which it should extend to be 25% of the original lease time, before the end of the session. So a 20 mins session would renew 5 mins before the end of the session.
2. The second code path is when you're connecting to an already existing session. This defines the time at which it should extend to be 20 mins before the end of the session.

**Extension Duration** - When the logic has determined it's time to extend, the current lease time is doubled. This allows session lengths to grow out of hand. For example, with the 2nd extension criteria from above, you could start a 10-minute session which you stay in for 21 mins and leave, the session length would have been extended to 80 mins. 

### **Expected Behaviour**
Auto-Renew default behaviour should be made more intuitive and consistent. 

The Azure Remote Rendering asset tool has user-defined extension duration and uses 25% of the extension duration as the trigger to extend. That seems like a reasonable logic. Although, arguably, in this instance, there should just be two user-defined values, extension time and time before the end of the session to auto-extend.

**Comment by FlorianBorn71** [comment]
Hi,
thanks for letting us know. We will do a pass over the logic as it seems to be quite unintuitive indeed. 
I'll keep you updated.

Cheers,
Florian

**Comment by FlorianBorn71** [comment]
Release 0.1.81 has been published:
https://github.com/Azure/azure-remote-rendering/releases
It has improved and very transparent session renewal code built into the samples
