### ISSUE TITLE
Unable to connect to a Storage Account from an ARR Account using IAM.

### ISSUE THREAD

**Issue by dykarohora** [Azure/azure-remote-rendering#2]
According to the documentation, I assigned three roles to the ARR Account for the Storage Account, but could not connect to the Storage Account.

I received the following response from the REST API.

```
{
    "error": "Unable to start conversion: Error accessing connected storage account - check if the ARR account has access to your storage account."
}
```

I got a similar error when using the Conversion.ps1 script.

I have assigned roles as follows, is there a problem with my settings?

<img width="1161" alt="role assign" src="https://user-images.githubusercontent.com/6583336/78952466-9653f800-7b10-11ea-8187-df70f37bf9e6.png">

The connection using SAS worked fine.

**Comment by ketankapila2** [comment]
I also receive this error. I was able to convert a file yesterday but continue to get the same error now.

**Comment by rikogeln** [comment]
Thanks for the reports! 
We are now aware of an internal issue which prevents the Azure Remote Rendering accounts from accessing connected storage accounts. 
We are working on a fix and will update once it is deployed. 

In the meanwhile please use the conversions/createWithSharedAccessSignature REST API to convert models

**Comment by archanaiyer** [comment]
We have deployed a fix for this issue. Please try it out again and let us know if it doesn't work. Thanks for reaching out!

FYI, For future debugging, if you can provide us with MS-CV that you receive in the response headers from the REST request, that will be super helpful for troubleshooting.

**Comment by dykarohora** [comment]
Thanks for the quick response!

I was able to connect the ARR and Storage Account using IAM. The conversion also works well.

But, I found a new problem. When connected with IAM, [the API checking the status of the conversion](https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/conversion/conversion-rest-api#poll-conversion-status) returns a 500 Internal Server error.

```
{
    "error": "Unable to get the status of conversion"
}
```

The MS-CV is as follows.

`NrkyMfZCjkSK2pgpOMR1SA.0`

**Comment by rikogeln** [comment]
@dykarohora can you please make sure that the regions in which you create the conversion and the region in which you query the status are the same? e.g. a conversion created in westeurope (https://remoterendering.westeurope.mixedreality.azure.com) cannot be queried in the southeastasia (https://remoterendering.southeastasia.mixedreality.azure.com) region. 

The same is true for sessions as well. All calls to the REST APIs need to go to the same region.

**Comment by rikogeln** [comment]
@dykarohora if the issue with the 500 on your conversions still persists please open another issue and provide the MS-CV values where it happens. Since the original issue with the IAM and ARR accounts was solved we will close this issue thread

**Comment by dykarohora** [comment]
I'm sorry for the delay in replying.

I tried your advice and the problem was solved. Thank you!
