### ISSUE TITLE
[Question] ARR for VR and Unity3d

### ISSUE THREAD

**Issue by frosadev** [Azure/azure-remote-rendering#20]
Hello guys,

I'm responsible for implementing industry 4.0 solutions in my company and, currently, we are working with AR/VR for many use cases.

After reading some documentation I saw that this service (ARR) will solve some of the issues we have on importing complex models into our XR environments.

Specifically in VR, mainly, we use HTC Vive Pro devices, Unity3d and Steam VR to build our experiences.

My question is:
Could we use ARR to remote render our CAD models for VR?

We have a pipeline built to retrieve and optimize the models from our PLM systems.

Most of the examples and demos I find are hololens 2 specific and, for that, we will definitely try this.

Thanks in advance.

**Comment by FlorianBorn71** [comment]
Hello and thanks for your request!
As of today, ARR only exists for HoloLens2 platform and Desktop PC. Other platforms are definitely on our radar and we want to prioritize them according to customer feedback. I can thus recommend that you leave some feedback about your requirements here: https://feedback.azure.com/forums/928696-azure-remote-rendering or upvote if appropriate.

Thanks!
Florian

**Comment by FlorianBorn71** [comment]
Regarding your question about remote rendering of CAD models. You can do that if the source models are either in FBX or GLTF/GLB file format: 
https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/conversion/model-conversion#supported-source-formats
