### ISSUE TITLE
Unity - Validate Project "Fix" buttons do not properly interact with Unity's undo system / modified state.

### ISSUE THREAD

**Issue by paco-ms** [Azure/azure-remote-rendering#22]
**Describe the problem**

Using the "Validate Project" window to fix issues like camera settings (by pressing the "Fix" buttons) does not properly mark the scene as modified.

Example: Open a new project, use that tool to fix some camera settings. Press Save Project. Close Unity. Reopen the project. See : none of the changes persisted.

**Provide additional information**

If you look at the Undo stack in Unity, you'll notice that the changes applied by the "Validate Project" tool do not appear there. Thus it seems like they are not being properly registered with Unity's undo system. That's probably the reason they don't get saved - Unity thinks no changes were applied.

**Comment by stefanhessel** [comment]
Hi paco-ms,

Thanks for your feedback!
I can reproduce the behavior and we will look into it.

Cheers,
Stefan

**Comment by stefanhessel** [comment]
The fix is part of [Release 1.0.7](https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.7). Thanks again!
