### ISSUE TITLE
[Remote rendering problem] Clipping Fade Colour and Length reset after toggling clip enabled state of a Clip Plane

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#23]
**Describe the problem**

If you create an ARR clip plane, setting the fade color and length on initialization the values are respected. 
If you then toggle the enabled state of the clip plane the fade color and length reset to what presumably is the default values.
If you try and set the values back to the ones set at initialization it fails to update (presumably due to a value change check). So to get the correct values again, you first need to set fade color and length to something different and then to the values you actually want.

This issue first presented after upgrading from 0.1.35 to 0.1.76 Both in Unity Editor and on Hololens. The latest version of the SDK has the same issue.

You can repro this in the Unity Editor using the following steps:
1. Start ARR session
2. Load up ARR model
3. Add the Remote Clipping Box script (from the showcase app) to the scene and position so that part of the object is clipped and part is visible.
4. Toggle the "Remote Clipping Box" game object off and on. Observe that the fade color and length have changed in the 3d view. It will now be a lighter blue and a larger fade length.

Note that the normal axis does not seem to get reset.

We are able to work around this issue for now, but it would be good to get it fixed.

**Comment by jumeder** [comment]
Greetings again @WikkidEdd. We fixed this bug as of [Release 1.0.1](https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.1). You should be able to remove your workaround now. Although recommended in general, there is no need to update to sdk 1.0.1 for this particular issue, as we fixed it service-side.
