### ISSUE TITLE
[Question] Is it possible to override a material with the TransparencyWritesDepth property during conversion?

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#25]
Is it possible to override a material with the TransparencyWritesDepth property during conversion?

I know it's not documented in the material override json schema, but I was hoping it was perhaps supported and just not documented. It feels like the sort of thing which should be set at conversion time as the model and not really something the user should need to adjust at runtime.

**Comment by jumeder** [comment]
Hi @WikkidEdd, the 'TransparencyWritesDepth' property is currently a runtime only feature. I'm pretty sure we have that on our backlog of feature additions, but it is not supported for conversion material overrides right now.

**Comment by WikkidEdd** [comment]
Ok, thanks

**Comment by jumeder** [comment]
Hi @WikkidEdd, just in case you are interested: We support the 'TransparencyWritesDepth' property as a material override as of [release 1.0.21](https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.21).

**Comment by WikkidEdd** [comment]
Thanks, that will be really helpful

. I'm subscribed to release updates so no new features can get by unnoticed ;)
