### ISSUE TITLE
[Remote rendering problem] Skybox for locally rendered content is disabled after connecting to ARR session

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#27]
**Describe the problem**
As already mentioned in this [issue](https://github.com/Azure/azure-remote-rendering/issues/26) we're using ARR on desktop with locally rendered content. If you have a Skybox set as the background type on the main camera, it will get changed to Solid Color when connecting to the ARR session. This is understandable behaviour on HoloLens, but on desktop, it's completely reasonable to want a Skybox background.

If the background type of the proxy camera is switched to the Skybox everything renders as one would expect. We've implemented this workaround locally, but it would be good to have it rolled into the main release.

Side note: It would be really useful if the ARR UPM package had its own git repo. As we've made changes to the package, we can't use the standard UPM upgrade procedure, and merging in our changes is all a bit messy. It would be much easier if we could fork a git repo.

Edit: I've just seen that the latest version of the package comes via the Mixed Reality Feature Tool, but same principle, hard to see what has changed and very clumsy to merge.

**Comment by FlorianBorn71** [comment]
At some point in the past we turned sky rendering off purposely because the sky box would just be rendered on top of the remote content and thus hide it. Maybe this has changed with either the Unity pipeline itself or the pipelines we are using by default. That said, I'll create a ticket to re-evaluate this and change it if it works (as your post suggests).

**Comment by FlorianBorn71** [comment]
SDK 1.0.6 has been released on github and it has the proposed change in it.
