### ISSUE TITLE
[Remote rendering problem] Black screen when connecting to ARR in a standalone windows build.

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#31]
**Describe the problem**

One of our users on our Windows 10 app found they got a black screen when they connect to ARR. Looking at the requirements and troubleshooting information, it is likely to be a driver or an h264 codec issue. In this instance, we were in the session with them so we could explain the issue, but if a user is on their own we want to be able to communicate the problem to them rather than just showing a black screen.

Questions:
1. Is it possible to detect when the video decoding has failed to initialize? There are no logs or errors printed out when the issue is happening.
2. Is there some compatibility test we can run when we first launch our app to warn the user before they've started and connected to an ARR instance?

**Provide additional information**

Session ID: c9d0e1af-99ce-4de5-90de-e69a29379acb

**Comment by FlorianBorn71** [comment]
Hello, 
there should be an automatic fallback to h264 so we'll do some investigations to find out. We'll keep you updated.

**Comment by WikkidEdd** [comment]
This turned out to be our issue caused by the changes we'd made for the skybox support mentioned in #27 . We definitely had this working without issue at one point, but it looks like a bad merge removed the code which set the main camera to solid color so the skybox was stopping anything from rendering.

We've upgraded to the latest version SDK now and all is working as expected.

Sorry for wasting your time.

**Comment by FlorianBorn71** [comment]
no worries, we applied fixes to our end as well. So if it works now with 1.0.6, then it's definitely also because of changes on our end ;-)
Florian

**Comment by FlorianBorn71** [comment]
Disregard my last answer, it makes no sense in the context of this ticket. I thought I answered to the sky ticket #27 ;-)
