### ISSUE TITLE
Conversion.ps1 localAssetDirectoryPath read as empty

### ISSUE THREAD

**Issue by efsjouw** [Azure/azure-remote-rendering#4]
The Conversion.ps1 gives me bunch of errors after running it.
arrconfig.json appears to pass all json validators I ran it through, but I noticed the path shows up as an empty string? I don't really have any powershell script knowledge to fix this or know why it would do this.

The example Unity application runs fine for me, I am now trying to convert and run my own model.

**Command:**
`powershell -ExecutionPolicy Bypass .\Conversion.ps1 -UseContainerSas  `

**arrconfig.json:**
`{
  "accountSettings": {
    "arrAccountId": "-removed-",
    "arrAccountKey": "-removed-",
    "region": "eastus2"
  },
  "renderingSessionSettings": {
    "vmSize": "standard",
    "maxLeaseTime": "24:00:00"
  },
  "assetConversionSettings": {
    "resourceGroup": "RemoteRendering",
    "storageAccountName": "remoterendertest",
    "blobInputContainerName": "arrinput",
    "blobOutputContainerName": "arroutput",
    "localAssetDirectoryPath": "D:/AzureRemoteRendering/azure-remote-rendering/Unity/Quickstart/Assets/Arena_Optimised_CutInHalf",
    "inputFolderPath": "",
    "inputAssetPath": "D:/AzureRemoteRendering/azure-remote-rendering/Unity/Quickstart/Assets/Arena_Optimised_CutInHalf/Arena_Optimised_CutInHalf.FBX",
    "outputFolderPath": "D:/AzureRemoteRendering/azure-remote-rendering/Unity/Quickstart/Assets/Arena_Optimised_CutInHalf/Output",
    "outputAssetFileName": ""
  }
}`

**Output (errors):**
`Successfully Loaded Configurations from file : D:\AzureRemoteRendering\azure-remote-rendering\Scripts\arrconfig.json ...

Populating Storage Account information ...
Could not retrieve storage account key for storage account named: 'remoterendertest' in resource group 'RemoteRendering'
Azure settings not valid. Please ensure the required values are filled in correctly in the config file D:\AzureRemoteRendering\azure-remote-rendering\Scripts\arrconfig.json
Uploading asset directory from  to blob storage input container ...
The property 'localAssetDirectoryPath' cannot be found on this object. Verify that the property exists and can be set.
At D:\AzureRemoteRendering\azure-remote-rendering\Scripts\Conversion.ps1:74 char:9
$assetSettings.localAssetDirectoryPath
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    FullyQualifiedErrorId : PropertyNotFound

Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At D:\AzureRemoteRendering\azure-remote-rendering\Scripts\Conversion.ps1:77 char:40
 ... utDirExists = Test-Path  -Path $assetSettings.localAssetDirectoryPath
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
     FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

Uploading 4 files to input storage container
Uploading file D:\AzureRemoteRendering\azure-remote-rendering\Scripts\arrconfig.json to input blob storage container
Set-AzStorageBlobContent : The term 'Set-AzStorageBlobContent' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\AzureRemoteRendering\azure-remote-rendering\Scripts\Conversion.ps1:97 char:17
         $blob = Set-AzStorageBlobContent -File $fileToUpload.FullName ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : ObjectNotFound: (Set-AzStorageBlobContent:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException

Unable to upload file arrconfig.json from local asset directory location  ...
Upload failed - exiting.`




Excuse the formatting I am having some troubles getting this output to look readable...

**Comment by rikogeln** [comment]
Hi, 
Did you follow the steps from 
https://docs.microsoft.com/en-us/azure/remote-rendering/samples/powershell-example-scripts ? 

(mainly installing the Az Module and calling Connect-AzAccount). 

Your json config migh be fine

**Comment by efsjouw** [comment]
Alright I missed that page, it is running now.

**Comment by efsjouw** [comment]
Mh now running it for the second time I get a 400 Bad Request when using the -UseContainerSas option?

`Unable to start conversion of the asset ...
********************************************************************************************************************
Response's MS-CV is 'PNV83Ui//02aAbRyl4o6SQ.0'
{
    "IsMutuallyAuthenticated":  false,
    "Cookies":  [

                ],
    "Headers":  [
                    "X-Content-Type-Options",
                    "MS-CV",
                    "Content-Length",
                    "Content-Type",
                    "Date"
                ],
    "SupportsHeaders":  true,
    "ContentLength":  281,
    "ContentEncoding":  "",
    "ContentType":  "application/json; charset=utf-8",
    "CharacterSet":  "utf-8",
    "Server":  "",
    "LastModified":  "\/Date(1586940715081)\/",
    "StatusCode":  400,
    "StatusDescription":  "Bad Request",
    "ProtocolVersion":  {
                            "Major":  1,
                            "Minor":  1,
                            "Build":  -1,
                            "Revision":  -1,
                            "MajorRevision":  -1,
                            "MinorRevision":  -1
                        },
    "ResponseUri":  "https://remoterendering.eastus.mixedreality.azure.com/v1/accounts/*-*-*-*/conversions/createWithSharedAccessSignature",
    "Method":  "POST",
    "IsFromCache":  false
}
********************************************************************************************************************
Invoke-WebRequest : {"error":"Unable to start conversion: Invalid request - the following errors occured:\n\tInvalid input path - check input.inputAssetPath for
errors.\n\tInvalid input folderPath - check input.folderPath for errors.\n\tInvalid output folderPath - check ouput.folderPath for errors."}
At D:\AzureRemoteRendering\azure-remote-rendering\Scripts\Conversion.ps1:171 char:21
+ ... $response = Invoke-WebRequest -UseBasicParsing -Uri $url -Method POST ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by rikogeln** [comment]
The formatting of the powershell output is not optimal. But if you look closely you see the following error message:
"Unable to start conversion: Invalid request - the following errors occured: 
Invalid input path - check input.inputAssetPath for errors.
Invalid input folderPath - check input.folderPath for errors.
Invalid output folderPath - check ouput.folderPath for errors."

This indicates that in your configuration you did not enter valid values. Please note that you also need to remove values marked as optional from the config. An example walkthrough is given in https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/convert-model

**Comment by efsjouw** [comment]
`    "resourceGroup": "RemoteRendering",
    "storageAccountName": "remoterendertest",
    "blobInputContainerName": "arrinput",
    "blobOutputContainerName": "arroutput",
    "localAssetDirectoryPath": "D:\\AzureRemoteRendering\\azure-remote-rendering\\Unity\\Quickstart\\Assets\\Arena_Optimised_CutInHalf",
    "inputFolderPath": "arenaConversion",
    "inputAssetPath": ".\\Arena_Optimised_CutInHalf.FBX",
    "outputFolderPath": "arenaOutput",
    "outputAssetFileName": "output.arrAsset"`

No matter what I do it always throw the invalid path errors for multiple fields. So no idea what is expected here.

**Comment by rikogeln** [comment]
Additional Documentation around the example scripts (in addition to the quickstart can be found here):
https://docs.microsoft.com/en-us/azure/remote-rendering/samples/powershell-example-scripts 
It states: 
"Make sure to properly escape backslashes in the LocalAssetDirectoryPath path by using double backslashes: "\\" and use forward slashes "/" in all other paths like inputFolderPath and inputAssetPath." 

I can see that inputAssetPath contains "\\" (also no need for the .)  - remove the slashes and dot please and turn your inputAssetPath into "Arena_Optimised_CutInHalf.FBX"

which other path errors occur? also can you please provide your arrconfig.json structure? (censor sensitive information like arraccount, key etc )

**Comment by efsjouw** [comment]
Alright this is my arrconfig

`{
  "accountSettings": {
    "arrAccountId": "-",
    "arrAccountKey": "-",
    "region": "eastus2"
  },
  "renderingSessionSettings": {
    "vmSize": "standard", 
    "maxLeaseTime": "00:30:00"
  },
  "assetConversionSettings": {
    "resourceGroup": "RemoteRendering",
    "storageAccountName": "remoterendertest",
    "blobInputContainerName": "arrinput",
    "blobOutputContainerName": "arroutput",
    "localAssetDirectoryPath": "D:\\AzureRemoteRendering\\azure-remote-rendering\\Unity\\Quickstart\\Assets\\Arena_Optimised_CutInHalf",
    "inputFolderPath": "D:/AzureRemoteRendering/azure-remote-rendering/Unity/Quickstart/Assets/Arena_Optimised_CutInHalf",
    "inputAssetPath": "D:/AzureRemoteRendering/azure-remote-rendering/Unity/Quickstart/Assets/Arena_Optimised_CutInHalf/Arena_Optimised_CutInHalf.FBX",
    "outputFolderPath": "D:/AzureRemoteRendering/azure-remote-rendering/Unity/Quickstart/Assets/Arena_Optimised_CutInHalf/Output",
    "outputAssetFileName": "output.arrAsset"
  }
}`

And is the error I receive with while running Conversion.ps1

{"error":"Unable to start conversion: Invalid request - the following errors occured:\n\tInvalid input path - check input.inputAssetPath for errors.\n\tInvalid input folderPath - check input.folderPath for
errors.\n\tInvalid output folderPath - check ouput.folderPath for errors."}

**Comment by rikogeln** [comment]
inputFolderPath inputAssetPath and outputFolderPath are relative paths in the storage containers and are not paths not on your local disk. 
The only path on your local disk is localAssetDirectoryPath. 

Looking at the example given in:
https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/convert-model 

your config should look something like this: 
```
{
	"accountSettings": {
		"arrAccountId": "-",
		"arrAccountKey": "-",
		"region": "eastus2"
	},
	"renderingSessionSettings": {
		"vmSize": "standard",
		"maxLeaseTime": "00:30:00"
	},
	"assetConversionSettings": {
		"resourceGroup": "RemoteRendering",
		"storageAccountName": "remoterendertest",
		"blobInputContainerName": "arrinput",
		"blobOutputContainerName": "arroutput",
		"localAssetDirectoryPath": "D:\\AzureRemoteRendering\\azure-remote-rendering\\Unity\\Quickstart\\Assets\\Arena_Optimised_CutInHalf",
		"inputFolderPath": "Arena_Optimised_CutInHalf",
		"inputAssetPath": "Arena_Optimised_CutInHalf.FBX",
		"outputFolderPath": "Arena_Optimised_CutInHalf_Output"
	}
}
```

This will:
- upload the contents of your local directory "D:\\AzureRemoteRendering\\azure-remote-rendering\\Unity\\Quickstart\\Assets\\Arena_Optimised_CutInHalf" to your blob container "arrinput" under a path of "Arena_Optimised_CutInHalf"
- Look for a model  inside this path called "Arena_Optimised_CutInHalf.FBX" to convert 
- If conversion suceeds output a model into the output container "arroutput" under a path of "Arena_Optimised_CutInHalf_Output"
- i removed the outputAssetFileName param and the service will deduce the output file name

**Comment by efsjouw** [comment]
Ah okay I was confused because the script appears to already start uploading, but I am not sure what that is meant for then. I manually created the folder and now it does not give me the path errors anymore. 

Thank you for the help.

**Comment by rikogeln** [comment]
With no additional command line parameters the script will always upload the files from the localAssetDirectoryPath - if you do not want this you can look at how to run individual stages of the script https://docs.microsoft.com/en-us/azure/remote-rendering/samples/powershell-example-scripts#run-the-individual-conversion-stages 

I also recommend to look at the source of the script and see how it is calling the REST API for conversions and rendering sessions 

If the issue has been resolved for you can you close the issue?

**Comment by efsjouw** [comment]
Mh yes, seems like I was a little bit too hasty. It now appears to keep adding the path to folder it tries to read from? I already restarted powershell as I thought it was caching the previous configuration.

I have a folder named Arena_Optimised_CutInHalf and the config is the same as the one you posted.
The stderr contains:

`
Error: ERROR: Failed to load file: Unable to open file "Arena_Optimised_CutInHalf/Arena_Optimised_CutInHalf/Arena_Optimised_CutInHalf.FBX".
`

**Comment by rikogeln** [comment]
can you provide the used arrconfig.json please?

**Comment by efsjouw** [comment]
Yeah I have no idea what is going on here the input path is set as Arena_Optimised_CutInHalf but just appears as Arena_Optimised_CutInHalf/Arena_Optimised_CutInHalf/Arena_Optimised_CutInHalf every time.
