### ISSUE TITLE
[Remote rendering problem] An error occurred while resolving packages

### ISSUE THREAD

**Issue by jackmca** [Azure/azure-remote-rendering#40]
The Unity Package Manager cannot locate this file in the manifest:
"com.microsoft.azure.remote-rendering": "file:../../MRPackages/com.microsoft.azure.remote-rendering-1.0.13.tgz", 

Try as I may, the usual fixes for other packages are not working for this project, such as deleting/altering the manifest and resetting the packages in the editor.

![Capture](https://user-images.githubusercontent.com/87106845/124856604-26bc0980-dfee-11eb-8f8c-16cfc4019b9d.PNG)

This issue appears in all example projects in the azure-remote-rendering repository.

Has anyone had similar issues?

Would appreciate any help, cheers.

**Comment by MalcolmTyrrell** [comment]
Hi. 

After cloning the repo, you need to run a download script before the projects will open in Unity. See the documentation here:
https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/render-model#clone-the-sample-app.

Can you check again after performing the DownloadUnityPackages.ps1 operation?

**Comment by jackmca** [comment]
Thanks for the reply, I was downloading the scripts previously but they were not working for some reason.

It turned out my issue was with permissions relating to powershell. This resource proved useful for me: https://superuser.com/questions/106360/how-to-enable-execution-of-powershell-scripts
