### ISSUE TITLE
Obselete references to World Anchor

### ISSUE THREAD

**Issue by konstyanchev** [Azure/azure-remote-rendering#41]
Hello,

I've tried the latest version of the sample project Tutorial-Complete and I'm running into an error related to the WorldAnchor class. If I understand correctly this class is part of the legacy XR system which is being replaced in favor of the new Open XR system. In the sample project, if you change the build target to Windows UWP you will get a compilation error in the file RemoteLightViewControllerHelper.cs which still references WorldAnchors.

What class should be used instead of WorldAnchors?

**Comment by stefanhessel** [comment]
Hello konstyanchev!

You're right, WorldAnchor is only supported in the legacy XR system. For the new XR SDK system you would use [ARAnchor from Unity​Engine.​XR.​ARFoundation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARAnchor.html) in place of WorldAnchor.

That said Tutorial-Complete has a few more dependencies that will prevent switching to OpenXR. For example it uses MRTK 2.5 but OpenXR support was only added in [MRTK 2.7](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-27-release-notes?view=mrtkunity-2021-05#whats-new-in-270). We have an update to our samples in the works that will switch them over to Unity 2020.3 and XR SDK.

Best regards,
Stefan

**Comment by stefanhessel** [comment]
Hi @konstyanchev!

our latest [release](https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.21) contains the sample updates for Tutorial-Complete and Quickstart.

Best regards,
Stefan
