### ISSUE TITLE
[Question] Returning triangle index of a raycast

### ISSUE THREAD

**Issue by sidoverflow** [Azure/azure-remote-rendering#43]
Hi folks. I am trying to obtain the [triangle index](https://docs.unity3d.com/ScriptReference/RaycastHit-triangleIndex.html) of a raycast hit on a remotely rendered model. Is this possible?

From what I understand, the `SubPartId` field from a [RayCastHit](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.remoterendering.raycasthit?view=remoterendering) is not the triangle index. Couldn't find anything else about this.

**Comment by MalcolmTyrrell** [comment]
Hi. 

There's no way to get the triangle index from the result of a raycast. The SubPartID can be used to identify which portion of the mesh at an entity was hit by identifying the material. See: 
* C++: https://docs.microsoft.com/cpp/api/remote-rendering/raycasthit#subpartid
* C#: https://docs.microsoft.com/dotnet/api/microsoft.azure.remoterendering.raycasthit.subpartid

The triangulation of meshes during conversion means that we do not guarantee a 1-1 mapping between faces in the source asset and at runtime. Additionally, no API is exposed for manipulating meshes at a per-triangle level, so knowing a particular triangle index would have little benefit.
