### ISSUE TITLE
RenderingSession.Disconnect() changed from blocking to async?

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#48]
**Describe the problem**

We recently noticed a problem with our app regarding our disconnect behavior. Upon digging into it, the issue was introduced when we upgraded from ARR SDK version 1.0.13 to 1.0.16. Between those two versions RenderingSession.Disconnect() seems to have changed from a blocking call to an async call.

In 1.0.13 you would call RenderingSession.Disconnect() and the ConnectionStatusChanged callback would fire while still inside the Disconnect call.

In 1.0.16 the call to RenderingSession.Disconnect() returns, then a frame or 2 later the ConnectionStatusChanged callback will fire.

This caused a race condition in our app which prevented users from reconnecting after manually disconnecting from a session. Now that we know about the behaviour change we can obviously put in a fix. 

However, we wanted to call this out as the behaviour change wasn't documented in the release notes which implies that it may not have been intentional. Furthermore, if it was an intentional change, then the Disconnect() should probably be renamed to conform with the other async calls (i.e DiconnectAsync) and return a Task<Result> so that it can be awaited.

**Comment by jumeder** [comment]
@WikkidEdd Yup, the latest release restores the old behavior.
