### ISSUE TITLE
[Question] Does Azure Remote Rendering support Windows 11?

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#49]
We've had a client run our desktop app on Windows 11 and ARR didn't work for them. We've not had a chance to investigate the issue yet, but thought it was worth checkig if Windows 11 is officially supported yet.

**Comment by ms-maxvollmer** [comment]
Hi! We are currently working on adding Windows 11 support and aren't aware of any major issues. If you can't resolve your issue please report a bug so we van investigate. If you find extra steps necessary to get ARR working in Windows 11, let us know so we can test this and if necessary update our documentation. Thank you!

**Comment by WikkidEdd** [comment]
Thanks @ChristopherManthei it was the missing Microsoft Visual C++ Redistributable, that saved me a bit of debugging.

I'd not seen this issue manifest like that before.
