### ISSUE TITLE
HybridRemoting error

### ISSUE THREAD

**Issue by InitusJames** [Azure/azure-remote-rendering#5]
Works fine in Unity but won't build in VS2019 due to this error.
- sideloading
- x64

LNK1104	cannot open file 'Microsoft.Holographic.HybridRemoting.lib'

**Comment by ChristopherManthei** [comment]
Hi,
We do not support UWP x64 yet. You will have to switch to UWP x86 for now. Please follow the steps [here](https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/deploy-to-desktop) if you want to deploy to desktop. I'll edit the documentation to make this limitation more clear. Sorry for the inconvenience.
