### ISSUE TITLE
[Question] VM Pooling Improvement Details

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#50]
> The VM pooling strategy has recently been significantly improved. As a result, the ARR service can provision 'standard' sessions in less than 10s most of the time. See API Changes for how existing custom code should account for this improvement.

We just saw the above improvements in the release notes and gave it test, sure enough, we had a session up and running within 10s. This is awesome, great work!

As part of our platform, we've implemented a scheduling service so you can "book" ARR servers and we'd make sure they'd spin up ahead of time. With the VM pooling improvements, it seems like most users wouldn't need to use the booking service. In order to inform our users when they should and shouldn't that feature, it would be helpful to get some more details.

Is there a limited number of instances that will be ready to spin up as quickly 10s? i.e if we have a 10 user session, is there a chance that there won't be enough ready-to-go instances in the VM pool?

If there aren't any ready-to-go instances, is the expected start-up time similar to what it has been previous 3-5 mins?

**Comment by ekmineev** [comment]
Our current pooling strategy is set up based on regional usage patterns and is subject to change. The goal is to have vast majority of standard sessions spin up in just a few seconds. However, it is still possible to see longer start times, especially around burst of usage like 10 requests for ARR servers coming in at the same time.
Note that typical start times for standard session came down significantly as well, and should be 1-2 minutes even without pooling in most cases with anything above 3 minutes being very rare.
The scheduling service you've implemented still makes sense if you want to guarantee fast availability of ARR servers to your customers.

**Comment by WikkidEdd** [comment]
Sounds good. Thanks for the extra information.
