### ISSUE TITLE
Flickering on Hololens 2

### ISSUE THREAD

**Issue by PowZone** [Azure/azure-remote-rendering#52]
The unity project: Tutorial-Complete works for remote rendering but flicker badly on Hololens 2.

Versions:
- Unity 2020.3.21f1
- MRTK 2.7.2
- OpenXR 1.2.8

Platform:
- HoloLens 2

**Comment by MichaelZp0** [comment]
Hello,

thanks for the report. This seems to be a problem with that Unity version. I could reproduce the problem on 2020.3.21f1 and 2020.3.22f1, but it works fine on 2020.3.13f1.  On my side the Unity startup logo is also affected by the issue, which also points in that direction. Can you confirm this on your end?

Greetings,
Michael Zappe

**Comment by PowZone** [comment]
Yes, I confirm. 

Solved using Unity 2020.3.20f1

**Comment by MichaelZp0** [comment]
Thanks for finding the last version that works :). We will update our documentation to specify, which version works and which doesn't. For the two versions that break, we will work with Unity to resolve this issue. If there is an update it will be reflected in the documentation.

Greetings,
Michael Zappe

**Comment by MichaelZp0** [comment]
I also found a bug in the more general MRTK repository regarding HoloLens 2 and Unity: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10288
I think this also would be a great place to look for updates on this situation too if you are also interested.
