### ISSUE TITLE
[Remote rendering problem] Connection lost when loading default model in Unity Quickstart project

### ISSUE THREAD

**Issue by pzyu** [Azure/azure-remote-rendering#53]
**Describe the problem**

A ConnectionLost exception is being thrown when trying to load the default model in the Unity Quickstart project.

![Connection lost](https://user-images.githubusercontent.com/18459487/141730081-6b4addab-000e-4cee-a675-db64e11cfd0f.PNG)

The project was set up based on this documentation: https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/render-model
I have made sure to validate the project using the built in tool under the RemoteRendering window in Unity, and I have also tried turning off my firewalls, but to no avail.

**Provide additional information**

Unity: 2020.3.14f1
ARR SDK: 1.0.31
Session ID: Arrc681f174aae224a700078fb5150c5013

**Additional context**

I see that a similar issue (#38) has been closed before, and I have tried both version 1.0.10, and 1.0.15 just to see if it was a version issue. However, all versions give the same ConnectionLost error.

Would appreciate any help on this!

**Comment by MichaelZp0** [comment]
Hello,
thanks for reaching out. 

It seems like the UDP traffic in your session is timing out. Is there any other device in your network stack that could block this? You already mentioned you tried disabling your firewall, but as the clues point in this direction I think a second look would not hurt. It could be that there is another firewall active in e.g. your router. If yes here would be the list of ports that need to be opened up https://docs.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements#network-firewall.

Some things that would help us troubleshoot the issue further would be:
1. Can you specify which type of network connection you are using (Wired, mobile 4G/5G)?
2. Can you try to connect through a different network?
3. Can you post a client trace here? (https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/performance-tracing?)

Greetings,
Michael Zappe

**Comment by pzyu** [comment]
Hello, I just tried switching to my mobile hotspot and it worked, so it probably is an issue with my network setup.

![image](https://user-images.githubusercontent.com/18459487/141768919-3b09326f-280d-4d34-a4e0-14603df978cc.png)

Thanks for the help!
