### ISSUE TITLE
Programmatically Show Children on remote objects

### ISSUE THREAD

**Issue by PowZone** [Azure/azure-remote-rendering#54]
In the editor you can use **Show Children** button, in the **RemoteEntitySyncObject** component selecting the remote object in play mode, but I can't find a way to do it programmatically on all remote objects and children of children at once.

**Comment by WikkidEdd** [comment]
That editor button just does this:
`foreach (var child in myTarget.Entity.Children)
 {
    child.GetOrCreateGameObject(UnityCreationMode.CreateUnityComponents);
 }`
 
 Where myTarget is a the RemoteEntitySyncObject.

If you wanted to include children of children then you would have to run the above recursively. Worth bearing in mind that if your model has 1000s of entities this would cause a performance spike.

**Comment by PowZone** [comment]
Thanks, it works perfectly.
