### ISSUE TITLE
[Remote rendering problem] MRC videos shows scaled down overlay in OpenXR

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#55]
After building a running the Tutorial-Complete sample and attempting to capture an MRC video the virtual content frame is scaled-down when overlayed over the video as soon as the runtime connects to the server.

Before Connection
![image](https://user-images.githubusercontent.com/1579290/144214369-5e4a7482-3be1-4a68-b720-8ef7ca5f907e.png)

After Connection
![image](https://user-images.githubusercontent.com/1579290/144214512-f4e3f2a4-9ad4-4c29-9dd6-95f64c77e42c.png)

This behaviour doesn't occur when running the same sample after switching over to the Windows XR plugin instead of OpenXR. It remains full screen even after connection.

Is this expected behaviour?

I noticed that there is no way to toggle PV Camera rendering for MRC in OpenXR. I wondered whether perhaps if it's on by default that accounts for the difference in behaviour?

As an aside, unrelated to ARR as such, I notice that in this sample the clear color for the MRC isn't alpha'd correctly in OpenXR. It's correct when using the Windows XR Plugin. I've definitely had OpenXR capture MRCs correctly in our own app. I'm curious as to what might be causing it in the sample. I've seen a few people in holodevelopers slack complaining about the clear color not being correct in MRC recently.

**Comment by FlorianBorn71** [comment]
Hi, thanks for the detailed information! 
The good news is that there is a fix for the large Fov already on the way for the upcoming release 1.0.34. We expect the new client release to be online by the end of this week. You'd need to upgrade because this is a client side fix. 
The reason why this happened is that the OpenXR version activates a "third eye" camera that has a larger Fov. With the fix we enforce the standard Fov from the device, so it will be the same behavior as before. 

As for the alpha values, we were not aware of any issue. We'll investigate now.

**Comment by WikkidEdd** [comment]
Great, I thought it might have been that "third eye" as you put it :) 

Do you know if there is any way to control disable that on OpenXR and use the old style way of reprojecting one of the eyes? I know the quality isn't as good, but it's cheaper than rendering the whole scene a third time.

**Comment by FlorianBorn71** [comment]
> use the old style way of reprojecting one of the eyes?
This is exactly what the fix is about. We cannot render a third view, so in ARR context MRC uses one eye.

Unfortunately there is currently no way to set this from the outside, but we'll reach out to the OpenXR team.

**Comment by FlorianBorn71** [comment]
Just fyi, release 1.0.34 is online now:
https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.34

**Comment by FlorianBorn71** [comment]
With regard to the alpha problem, I heard today that it was a bug in the OpenXR binding that has been resolved in 1.2.0.
You should be able to upgrade to that version and then the problem should be gone.
