### ISSUE TITLE
RemoteRendering_Startup 0x80010106 : 'Cannot change thread mode after it is set.'

### ISSUE THREAD

**Issue by fieldsJacksonG** [Azure/azure-remote-rendering#60]
Attempting to integrate ARR with an existing engine.  When I call StartupRemoteRendering from the engine's game thread, I get an RPC_E_CHANGED_MODE error. 

I can work around this by calling StartupRemoteRendering on a background thread, but then my ConnectionStatusChanged immediately disconnects after attempting a connection.

Can StartupRemoteRendering be called from a background thread?
Any way to get additional information about why a connection fails? (beyond the Result output in the ConnectionStatusChanged event)

**Comment by ChristopherManthei** [comment]
Hi @fieldsJacksonG , sorry to hear you are running into issues. ARR requires a [multithreaded apartment](https://docs.microsoft.com/en-us/windows/win32/com/multithreaded-apartments) on every thread that it is used on. If you get this error, some part of your code probably already initialized the thread as a single threaded apartment. You will need to change the code to call [CoInitializeEx(NULL, COINIT_MULTITHREADED)](https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex) instead.
As for calling StartupRemoteRendering on a background thread, generally all ARR calls should be done from the same thread that you called StartupRemoteRendering on.

**Comment by fieldsJacksonG** [comment]
Thanks!  Issue was from calling StartupRemoteRendering after xrCreateInstance
