### ISSUE TITLE
[Remote rendering problem] AuthenticationFailed after app has been asleep for a long time

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#62]
**Describe the problem**

We've noticed some failures connecting to ARR Sessions recently with the error RRSessionExpception AuthenticationFailed. Digging into it, it appears to happen after the app has gone to sleep and then resumes after a long period of time.

User flow would be something like:
1. Runs the app
2. Start and connect to ARR session
3. Disconnect and Forget ARR Session
4. App goes to sleep
5. 48 hours have passed
6. App wakes 
7. Attempts to connect to an ARR Session.
8. RRSessionExpception AuthenticationFailed

The same flow doesn't trigger the authentication failure if only a short amount of time has passed. This makes me wonder if it's an access token that has expired or something.

Is there something else that we need to call when ending the session?

**Comment by FlorianBorn71** [comment]
Hi Edd,
I will have one of our engineers comment on this.
Cheers,
Florian

**Comment by ekmineev** [comment]
Hello Edd,

> This makes me wonder if it's an access token that has expired or something.

Authentication tokens are valid for 24 hours after issue. We'll make sure it is clearer called out in [our authentication documentation](https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/authentication), at the moment that page links to [Azure Spatial Anchor's docs](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/authentication) that, in turn, mentions the 24 hour expiry.

For the long running application, we recommend implementing auth token auto-renewing logic, or requesting new auth token on every request to our REST API endpoint. 

> Is there something else that we need to call when ending the session?

As long you are explicitly stopping the session, or allowing it to reach the expiry time you have configured it with, there is nothing else to call. Maximum duration for rendering sessions is [24 hours](https://docs.microsoft.com/en-us/rest/api/mixedreality/2021-01-01/remote-rendering/create-session#create_session_settings).

Hope this helps,
Katya

**Comment by WikkidEdd** [comment]
I've made some modifications to the ARRServiceUnity which lets me dispose of the RemoteRenderingClient so that I can ARRServiceUnity.Initialize again without issue. I presume this would re-initialize the authentication thus renewing the token internally? Assuming this is a safe/sensible thing to do, could that be added to the SDK?

Having done this investigation I can also see that we should switch to using an access token provided via our backend. (We didn't have the backend when we first implemented ARR so we had to use AccountKey, then the implementation never got updated)

**Comment by FlorianBorn71** [comment]
Hi Edd, it would be indeed interesting to see your changes. Would you mind creating a PR in github so we can have a look?
Cheers,
Florian

**Comment by WikkidEdd** [comment]
It's a change to sdk package so I can't make a PR for that can I?

It's super simple so I can just stick it here anyway. I just added this function to ARRServiceUnity to dispose of the RemoteRenderingClient. This allows me to safely call ARRServiceUnity.Initialize with a new access token.

```
public void DisposeOfClient()
{
    if(Client != null)
    {
        Client.Dispose();
        Client = null;
    }
}
```

I think without this function the only other way to achieve it would be to destroy the ARRServiceUnity component and then re-add it.

**Comment by ekmineev** [comment]
Hi Edd, 

> Having done this investigation I can also see that we should switch to using an access token provided via our backend. (We didn't have the backend when we first implemented ARR so we had to use AccountKey, then the implementation never got updated)

Exactly right! This is indeed our recommendation for production applications. Please consider switching from using account keys in client SDK to Azure AD service authentication, as noted https://docs.microsoft.com/en-us/azure/remote-rendering/tutorials/unity/commercial-ready/commercial-ready#security. 

Thank you, 
Katya

**Comment by FlorianBorn71** [comment]
Hi Edd, your code makes sense, but we'll have a look if there is a more user friendly way to do the disposing automatically, e.g. when setting a new client. I'll keep you posted...

**Comment by stefanhessel** [comment]
Hi Edd, our [latest release](https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.49) contains the addition you suggested. It's called `ARRServiceUnity.Deinitialize` to match the corresponding `Initialize` member.

Thank you for your contribution!

**Comment by WikkidEdd** [comment]
I'd spotted that! Really helpful, thanks 🥇
