### ISSUE TITLE
[Question] Can you make Bounds and Double3 structs not readonly please?

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#64]
We want to be able to serialize/deserialize a model's bounds to json so we can see the representation of the bounding models without being connected to ARR. At the moment Bounds and Double3 are readonly so it fails to deserialize if we just use the Bound struct directly. For now, we've just removed that keyword so it works, but it's something that must be maintained with every SDK upgrade which is prone to error.

We could obviously just create our own bounds struct and populate it from the ARR bounds struct, but it would be cleaner if you could remove the readonly keywords. Is that something you would consider?

Thanks

**Comment by FlorianBorn71** [comment]
Hi,
I think the reasoning was some API requirement. But from a very practical point of view, it indeed does not make too much sense in this context. Let's see if we can change it, I can't promise at this point though.

Cheers,
Florian

**Comment by FlorianBorn71** [comment]
good news, we decided to drop the read-only attributes. While it was a recommendation by the Azure guidelines, we think it does not serve any real purpose here, since structs are passed by value anyway.
It will be removed as per next release.

**Comment by FlorianBorn71** [comment]
closing this ticket since 1.0.51 with these changes has been released today. Enjoy!
