### ISSUE TITLE
Sky light/reflection orientation

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#65]
Hi,

We're building a highend product visualisation and we plan to use a custom sky texture for the first time. The sky texture is a studio lighting style setup and the lighting is quite directional. It occurred to me that I'm not aware of any way for specifying the orientation of the sky lighting in ARR. I assume that by default the sky light is oriented based on one axis of the Hololens reference frame, but obviously, this is different depending on where your HL is when you start the app, so not ideal for consistent lighting, between runs of the app or between users.

For locally rendering, the models and the lights are all parented to the same object which is anchored and shared amongst users, this ensures the lighting is consistent across all devices.

We can mirror that same behavior with ARR have model and directional lights parented to the same object, but since the sky light is a global property I don't think it could be setup in the same way.

The only thing I can see in the docs which may address this issue is the Stage Space settings, but that is experimental and like a drastic change in order to get the lighting orientated correct.

Is there solution to this already and if not, is it something that could be added?

Thanks,

Edd

**Comment by jumeder** [comment]
@WikkidEdd would your use case require the skybox to be transformed continuously, meaning at most each remote frame rendered, or is the functionality you are looking for rather a low-frequency change, e.g. setting the intended orientation at startup so it matches up on all your users and then never changing it again?

**Comment by WikkidEdd** [comment]
It would definitely be low frequency. We have just one spatial anchor and all the content is parented to that so the lighting would only need to update if the anchor changes. In our case, that would either be if the user decides to reposition the anchor (this generally only happens once at the start of the session) or the OS updates the anchor because the tracking changed. 

I was thinking along the lines of a world direction vector that you can set on SkyReflectionSettings. Although, in our case, we'd only need a vector locked in the XZ plane, so it could be angle around the Y axis instead of a vector.

**Comment by FlorianBorn71** [comment]
Hi, the client side release from today [ARR 1.0.57](https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.57) has the new API for sky rotation (see release notes). Enjoy!

**Comment by WikkidEdd** [comment]
Awesome, thanks a lot 👍
