### ISSUE TITLE
Strange behaviour with multiple arrAssets generated from the same source file

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#66]
We have two glbs (A and B) that have been created from the same blender file. They contain the same model (mesh, materials, textures, hierarchy) the only difference is that we've moved the transform nodes around in file B to give us a more curated exploded view. These files have then been converted to arrAssets

When running on the HL we first load in model A, we then disable model A and then start loading model B. Instantly, before model B has finished loading, parts of the model are already visible in the location of model A. When model B has finished loading it has both some of model A visible and all of model B visible. 

We then attempt to hide model B and show model A, but we end up with all of model A visible and part of model B. Then eventually if we hide model A and show model B only model B is shown and everything works as respected.

It's kind of hard to explain just in words, we have screenshots that make it more clear what is going on, but it is a client model so we can't share them on here. I can send them directly if you let me know who to send them to.

I assume it's caused by some confusion over model identifiers as both arrAssets came from the same source model. Is there anything you can recommend as a workaround to ensure that the models are treated completely differently?

**Comment by WikkidEdd** [comment]
We've managed to create a test file that produces the same issue. [ARR_Monkey_Test_Posed.zip](https://github.com/Azure/azure-remote-rendering/files/8247613/ARR_Monkey_Test_Posed.zip)

First model loaded
![20220314_191829_HoloLens](https://user-images.githubusercontent.com/1579290/158236923-aa4885b3-ff8a-4b29-bc45-52cca2fc85cc.jpg)

First model hidden and second model loaded in. Both models visible, but first row of heads missing from first model
![20220314_191914_HoloLens](https://user-images.githubusercontent.com/1579290/158237353-951efde8-6755-4fef-b1b9-9e1fbbfa4fda.jpg)

Second model hidden and first model visible. Both models visible, but first row of head missing from second model
![20220314_191925_HoloLens](https://user-images.githubusercontent.com/1579290/158237966-e80d87f8-7963-4d45-88ba-5e9b31e4b005.jpg)


First model hidden again and second model shown. Now looks correct
![20220314_191937_HoloLens](https://user-images.githubusercontent.com/1579290/158237562-19333794-04a3-4575-aaa7-7f654e6446d1.jpg)


(There is something strange going on with the MRCs too, but we can dig into that another time)

**Comment by MichaelZp0** [comment]
Thank you for the test model. I'll definitely use that then to reproduce it.

**Comment by WikkidEdd** [comment]
@MichaelZp0 the multiple objects from same source is a red herring. It can be produced by simply loading in one of the models and hiding it. You'll see that it leaves part of the model visible.

I've just done some other tests and found that a previously converted model doesn't exhibit this problem, but converting the exact same model again and using that has the problem.

So it would appear to be a bug in the conversion process. Given that this is affecting all models this have become a pretty high priority for us to get this fix.

**Comment by MichaelZp0** [comment]
Sorry I still cannot reproduce that behavior, some clarification would be necessary.

Through which mechanism are you hiding the game objects (Entity enable state, Unity enable state, ARRHierarchicalStateOverrideComponent...)?

On which level of the object are you doing the hiding (model root or some parent entity)?

**Comment by WikkidEdd** [comment]
Disabling the gameobject which has the RemoteEntitySyncObject on it. 

For clarity I've created a new issue #67 which better reflects the actual problem. As it seems to be more of a general issue than the niche problem I initially thought it was. I'll close this issue.
