### ISSUE TITLE
Models that have been converted recently don't completely hide when it is disabled

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#67]
We've found an issue where models which have been converted in the last week or so (maybe earlier than that) don't get hidden properly when disabling the game object. In order to have them fully hide, they need to be reenabled and disabled again. The same models which had been converted in the past are able to be disabled correctly, so it seems like a conversion bug that was introduced recently.

This is a **high priority** issue for us as our app is designed to look through multiple ARR models. With this bug, rogue geometry is left on which can render over the model you want to see. Furthermore, can push us over the 20m poly count for standard which results in checkerboard rendering.

We've tested ARR SDK 1.0.41 and 1.0.51 and also tested all 3 scene graph modes when converting the model.

Repro steps:
1. Convert attached model for ARR
2. Load model into application ensuring there is a RemoteEntitySyncObject for the root object
3. Disable the game object which has the RemoteEntitySyncObject on it.

Screenshots
Before disabling:
![20220315_143934_HoloLens](https://user-images.githubusercontent.com/1579290/158391918-80d49744-73f9-442a-838b-f038a23aecb7.jpg)

After disabling:
![20220315_144012_HoloLens](https://user-images.githubusercontent.com/1579290/158391940-bca2bcc2-8b05-495a-83bb-506cd88e77b9.jpg)

[ARR_Monkey_Test.zip](https://github.com/Azure/azure-remote-rendering/files/8253980/ARR_Monkey_Test.zip)

**Comment by WikkidEdd** [comment]
Ah right, I was just trying to reproduce it in the Quick Start app and noticed it didn't reproduce in there and wondered if that component might be the reason.

I'll look into implementing that fix, the problem is with our app store build so would be a couple of days for it to get through submission. So you fix might come before the update has been pushed. 

Please keep us updated on your progress so we can assess our options.

**Comment by MichaelZp0** [comment]
Okay I did not find the root cause of the problem, but still something that mitigates the problem for now. We will start a release as soon as possible and it will be public around middle of the day of this week's Friday (CET).

**Comment by WikkidEdd** [comment]
Great, thanks for the quick turn around.

**Comment by WikkidEdd** [comment]
Will the fix require us to convert the models again?

**Comment by MichaelZp0** [comment]
As far as I can tell, yes you'll need to convert the 'broken' models again. It shouldn't affect models, that were converted before the problem surfaced.

Also as a side note. This change did increase load times of models again, but we are trying to find the root cause to put it back in the next release or the release after that, so that models will be loaded fast again. This time of course with properly converted models :).

**Comment by MichaelZp0** [comment]
You can test it now if you want. The release is out.

**Comment by WikkidEdd** [comment]
Great. I can confirm that it is fixed after re-converting the models 👍 

Thanks for the quick turnaround.

**Comment by WikkidEdd** [comment]
Can I just clarify that the fix is serverside and would not require us to upgrade to the 1.0.53 that came out today?

**Comment by FlorianBorn71** [comment]
Exactly, and it has been deployed now! So no need to update client side.
