### ISSUE TITLE
[Remote rendering problem] Glitch with model rendering

### ISSUE THREAD

**Issue by reneschulte** [Azure/azure-remote-rendering#7]
**Describe the problem**

I got a model from SketchFab which renders with some weird glitch/artifact using ARR.

See this MRC showing the issue mentioned in-action:
https://1drv.ms/v/s!AiU59qTROkNXmN0d2fic5BJY4-9jbg?e=eacPsS

This is the model I'm using
https://sketchfab.com/3d-models/half-view-of-sars-cov-2-virion-c9ac6b27205a445baa913d6b93989966

**Provide additional information**

This is the model I'm using. Tried FBX and glTF for the conversion. 
https://sketchfab.com/3d-models/half-view-of-sars-cov-2-virion-c9ac6b27205a445baa913d6b93989966

Just using the sample and followed the process to convert which I have been successfully using many times before with other models from SketchFab.

**Additional context**

**Comment by jumeder** [comment]
Hello Rene, thank you for reporting the issue and for the additional material you provided. I'll update you as soon as we know more about this.

**Comment by reneschulte** [comment]
Just tried with a model I converted a few weeks ago and that worked fine back then but now same client code shows the same glitch, so must be some issue that was introduced in the remote rendering. 

This is the model which looked fine a weeks ago and now shows the same glitch with ARR:
https://www.youtube.com/watch?v=xiVMOYpjdMo

**Comment by jumeder** [comment]
We can produce the issue as well on our side and are investigating causes and solutions.

**Comment by jumeder** [comment]
Rene, just to clarify your second comment: Did you reimport the model which worked a few weeks ago or did you reuse the model conversion output from back then?

**Comment by reneschulte** [comment]
@jumeder I've used the model conversion output from back then, so it's not in the conversion process I guess.

**Comment by maapp** [comment]
Hi Rene,

the issue should be mitigated if you start a new session now. Sorry for the inconvenience!

Bye,
Marc

**Comment by reneschulte** [comment]
Confirmed it works. 

Danke!
