### ISSUE TITLE
[Question] Support for Direct3D 12

### ISSUE THREAD

**Issue by NoTuxNoBux** [Azure/azure-remote-rendering#73]
Unity 2021.3.0 is now LTS and Unity 2021 added support for Direct3D 12 on OpenXR and the HoloLens 2, but if I test running my application with it enabled, starting a remote rendering session seems to immediately crash the application. The last thing I see is the following:

```
Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak
Unity graphics device:
ID: 1161245232 Name: Qualcomm(R) Adreno(TM) 630 GPU
Type: Direct3D12 Version: Direct3D 12 [level 12.1]
[XR] [Mixed Reality OpenXR Input]: Handle Event received with eventType[1363496514], DeviceId[1], Buffer Size[1].
[XR] [Mixed Reality OpenXR Input]: Handle Event received with eventType[1363496514], DeviceId[0], Buffer Size[1].
```

This is not (necessarily) a bug report or support request, but because of this crash I was wondering if using this package in Unity with the Direct3D 12 rendering back end is supported, or if it is on the roadmap.

Thanks!

**Comment by FlorianBorn71** [comment]
Hello,
Unfortunately there is currently no DX12 version of ARR available and it is currently also not on our short-term roadmap.
That said I 'd recommend creating and upvoting an item in the [ARR forum](https://feedback.azure.com/d365community/forum/46aa4cc0-fd24-ec11-b6e6-000d3a4f07b8) so we can consider it for future planning.
Thanks for your feedback!

**Comment by NoTuxNoBux** [comment]
Thanks for the update, as suggested I [posted an idea in the forum instead](https://feedback.azure.com/d365community/idea/a707294b-c2bb-ec11-a81b-6045bd7ac9f9).
