### ISSUE TITLE
[Conversion Problem] Conversion IDs in results.json files don't match the IDs of the jobs they correspond to

### ISSUE THREAD

**Issue by robbbbbb** [Azure/azure-remote-rendering#83]
**Describe the problem**

This may just be undocumented behaviour rather than a problem.

When a conversion is successful it emits a `<outputfilename>.result.json` file in to the specified output container. The contents of that file are documented here https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/conversion/get-information#information-about-a-conversion-the-result-file

On recent successful conversions I've noticed an extra (I think undocumented) line which seems to be trying to give the conversion ID that produced the results file. However, the ID given never corresponds to the conversion that produced the file.

**Provide additional information**

For example, starting a conversion with the REST API I got this result (note, the `id` property value)
```
{
    "id": "e28e49d2-28d6-44dc-a973-ab3d14d941bb",
    "creationTime": "2022-07-19T09:04:40.4170167Z",
    "settings": {
        "inputLocation": {
            "storageContainerUri": "https://<redacted>.blob.core.windows.net/arrinput",
            "blobPrefix": "test-singlefile/",
            "relativeInputAssetPath": "Duck.glb"
        },
        "outputLocation": {
            "storageContainerUri": "https://<redacted>.blob.core.windows.net/arroutput",
            "outputAssetFilename": "test-conversion.arrAsset"
        }
    },
    "error": null,
    "status": "NotStarted"
}
```

And upon successful completion the test-conversion.result.json file had the following contents:

``` 
[
  {"conversionId":"96C56D54-F292-524F-8368-6CAF58A0E6A9"},
  {"result":"succeeded"}
]
```

We don't *use* this line from the results.json file, and it's not mentioned in the docs as far as I can see, so I guess it's possible it refers to some other entity and users of the API should just ignore it, but I thought I'd mention it, in case it revealed something else going on.

**Comment by FlorianBorn71** [comment]
I got feedback from an engineer and it turns out this is a different (internal) Id that cannot be used for matching the conversion Id. So in case you don't intend to use it, I'll rather go and clarify in the documentation.
Thanks for raising this, it's very valuable feedback!
Florian

**Comment by robbbbbb** [comment]
Thanks @FlorianBorn71 we definitely don’t use it so totally fine by us.
