### ISSUE TITLE
[Question] Voice support for Unity  Showcase application

### ISSUE THREAD

**Issue by Cangi** [Azure/azure-remote-rendering#87]
Looking through the updates to the unity showcase application I have seen that it integrates photon voice to perform voice communication between participants but in order to use it on HoloLens it would require a photon addon which is only available to Photon Industries Circle

Is there a way to get access to the package without joining the photon Industries Circle?

**Comment by mariambecet** [comment]
Hi. It is possible to get Photon Voice 2 for free from the Unity Asset Store (https://assetstore.unity.com/packages/tools/audio/photon-voice-2-130518). Please note that the current Showcase version uses Photon Voice  v2.31 and the latest v2.50 has some breaking changes that need to be manually corrected. We will upgrade Showcase app in a future release.

**Comment by Cangi** [comment]
Hi,
I understand that but if you want to use it on a HoloLens 2 the photon voice 2 documentation is saying that an extra addon is required.
# https://doc.photonengine.com/en-us/voice/current/getting-started/voice-intro#supported_platforms

**Comment by mariambecet** [comment]
Hi, thanks for the reply. The addon is required for building ARM64. Hololens2 supports ARM (32-bit) builds as well. If you don't have other dependencies that require 64-bit builds and are able to build for ARM instead, the free version of Photon Voice 2 will work. This was tested with Photon Voice 2 v2.31 though. I will give an update after testing the latest version v2.50.
