### ISSUE TITLE
[Conversion Problem] Joined meshes can not be moved

### ISSUE THREAD

**Issue by MaStoljar** [Azure/azure-remote-rendering#88]
After combining multiple meshes into one mesh with the blender join functionality, the possibility of using the "move part" functionality breaks. 

How to reproduce:
Attached are three files: allCombined.glb, consoleFront_floor_combined.glb and Parts.blend

After converting the two glb files into arrAsset, the allCombined.glb can not be moved after being loaded into the scene with the move tool, while the consoleFront_floor_combined.glb is working fine.

To recreate the glb files, the attached blender file can be used. It contains three separate meshes (console_mid, console_front, and floor). If you select all, hit Ctrl+J in blender, export it as glb (same as allCombined.glb), and run the conversion with default settings, the move behavior did not work for me.
[Meshes.zip](https://github.com/Azure/azure-remote-rendering/files/10059856/Meshes.zip)

**Comment by WikkidEdd** [comment]
This is expected behaviour. You can only move individual meshes in the hierarchy. As you've described (and as seen in allCombined.glb) you've merged it into a **single** mesh, so the individual parts can no longer be selected. 

In the consoleFront_floor_combined.glb file you've merged console front and floor and left the console mid as it's own object. In this case you'll be able to move console front and the floor as one part and the console mid as another part. 

You see the exact same behaviour in Blender, after you've pressed Ctrl+J with all the parts selected you have a single mesh in the hierarchy and the individual parts are no longer selectable or moveable on their own. This is common behaviour across all model viewers, game engines etc.

What are you trying to achieve by merging them into a single mesh?

**Comment by MaStoljar** [comment]
But even the allCombined.glb should be moveable with the "move all" functionality, which is impossible.

I have a bigger model and want to combine semantic connected parts into one, so I can move them all together and reduce the amount of interactable parts. In the final setup, I would have five parts consisting of multiple meshes combined via blender. For some parts, this is already working, but for some parts, it brakes the interaction.

The files I sent were just the smallest possible example I could extract.

**Comment by WikkidEdd** [comment]
Ah I see. I thought were you saying you were combining all the parts and still expecting to be able to move individual parts.

Your use case makes sense.

Is your observation that as soon as it turns into a single mesh that the move functionality breaks or do you find that within a bigger model when some combined parts can work and some don't?

**Comment by MaStoljar** [comment]
The move functionality works for some combined meshes and some not. The strange part is that the move function works fine for some huge combined meshes, but for some dedicated meshes, it breaks after combining them. So in my example, I can not combine console_front and console_mid, but each mesh of them with the floor.

**Comment by stefanhessel** [comment]
Hi, thanks for reaching out! We tried to reproduce the behavior you describe but so far were not able to. Can you please provide some more detail? We'd be especially interested in
- The conversion settings you used
- The steps to reproduce the behavior e.g. what kind of app did you use on which platform, how are you loading models, etc.

Thank you!

**Comment by MaStoljar** [comment]
I use the default settings. As shown below
![image](https://user-images.githubusercontent.com/100917068/203365478-61eab08f-f4a3-4c66-a55c-5ff7cbd75c77.png)
![image](https://user-images.githubusercontent.com/100917068/203365587-8b5bc6dd-fa83-4773-be27-efe0f9bcae3a.png)

The steps to reproduce are the following:
- Use ARRT to convert model
- Using Unity example "Show Case App" on Windows machine
- Target Platform in Unity is UWP because we build it for HoloLens2
- Starting play mode in Unity Editor
- Connect to ARR Service.
- Load Model with UI in play mode
- Switch to Tools and select move part

https://user-images.githubusercontent.com/100917068/203412343-0ded20ba-faf9-45dd-99dd-9eb4eb3a84af.mp4

**Comment by WikkidEdd** [comment]
I can confirm we can reproduce this in our app. We just came across a model being used which exhibits similar problems where certain parts of the model don't return a raycast hit (aka no selectable)

We just tried @MaStoljar's allCombined.glb model and we see the exact same behaviour, but the whole model is not collidable.

**Comment by FlorianBorn71** [comment]
Thank you @MaStoljar and @WikkidEdd for all the data and additional insights! 
In the meanwhile we were able to reproduce the problem that was reported initially, i.e. raycasts do not work for certain meshes. We are working on it. @MaStoljar, would it be sufficient if the fix in the service is available next week, or is there some urgency?

**Comment by MaStoljar** [comment]
Next week would be fine @FlorianBorn71. Thank you for the quick response

**Comment by FlorianBorn71** [comment]
Hi @MaStoljar , hi @WikkidEdd!
A server-side fix has been deployed, so raycasting should work as expected now. No need to re-export the model(s).
Sorry for the inconvenience and thanks for the great repro case!

Florian

**Comment by WikkidEdd** [comment]
I can confirm this has fixed our issue. Thanks 👍

**Comment by MaStoljar** [comment]
Hi @FlorianBorn71, I confirm that it fixed the stated issue. Thank you !
