### ISSUE TITLE
[Question] Why no WinMR Immersive VR support? 

### ISSUE THREAD

**Issue by reneschulte** [Azure/azure-remote-rendering#9]
ARR can be deployed as Windows desktop app but only without VR/WinMR support as mentioned here: https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/deploy-to-desktop

Out of curiosity I tried it and got a bunch of exceptions when debugging. 

Why is no stereo / VR / WinMR support for desktop provided and any ETA for it?

**Comment by maapp** [comment]
Hi Rene, I currently don't have an ETA for you on this. There are some interesting technical challenges: VR has a higher framerate, higher resolution etc. This poses challenges on a video encoding & bandwidth level.

Besides that immersive VR will potentially require additional rendering features to create a compelling experience.

However it would be really interesting to see how many folks are interested in this as we definitely want to be where our customers are. Do you mind filing an item on our Azure feedback page: https://feedback.azure.com/forums/928696-azure-remote-rendering so we can gauge interest?

**Comment by reneschulte** [comment]
Sure. Posted here: 
https://feedback.azure.com/forums/928696-azure-remote-rendering/suggestions/40624849-winmr-immersive-vr-support
