### ISSUE TITLE
[Remote rendering problem]QuickStart - RemoteRendering object has missing script

### ISSUE THREAD

**Issue by ShirleyMaX** [Azure/azure-remote-rendering#91]
When I open up the QuickStart project, RemoteRendering object missing a mono script.
![image](https://user-images.githubusercontent.com/71268749/214358236-005d983f-937e-4c39-9d04-23ea9dc39261.png)

Therefore causing a missing assembly reference problem when compile.
![image](https://user-images.githubusercontent.com/71268749/214358741-a17a4f9e-d7b6-445b-b8f9-465aca5013dd.png)

Please let me know if I am missing any steps. Appreciate the help!!

**Comment by WikkidEdd** [comment]
It looks like you've not run the command line that sets up the Unity packages. See this link here for how to set up the samples

https://learn.microsoft.com/en-us/azure/remote-rendering/quickstarts/render-model#clone-the-sample-app

The key line is the following which downloads all the packages.
`powershell -ExecutionPolicy RemoteSigned -File azure-remote-rendering\Scripts\DownloadUnityPackages.ps1`

I would recommend following along with the rest of the linked page to see how to setup the rest of the Quick start project

**Comment by ShirleyMaX** [comment]
> 

Hi Edd,
Thank you so much for the quick help! I have followed the steps and now successfully set up the project!
